blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://github.com/rwightman/pytorch-image-models/discussions
    about: Issues are for features and bugs. Questions can be asked in Discussions.
