#!/usr/bin/env python3
"""Generate the per family model pages of the timm docs from code and result data.

Each family page (``hfdocs/source/models/<slug>.mdx``) is built from:
  * a short hand written entry in ``FAMILIES`` below (title, category, 1-3 sentence description),
  * the model module docstring (paper references, BibTeX),
  * the model registry and pretrained configs (architectures, weights, licenses, Hub ids),
  * ``results/results-imagenet.csv`` (ImageNet-1k top-1) and a ``results/benchmark-infer-*.csv`` (params, GMACs),
  * a functional probe of the model API on a randomly initialized, smallest architecture per model class.

The probe results are also rendered as a support matrix (one row per family / model class) and spliced into
``hfdocs/source/model_api.mdx`` between the ``<!-- BEGIN GENERATED SUPPORT MATRIX -->`` /
``<!-- END GENERATED SUPPORT MATRIX -->`` markers, and optionally written to ``--matrix-file``.

Run from the repository root, against the repository timm (not an installed release), offline:

    PYTHONPATH=. python hfdocs/generate_model_docs.py
    PYTHONPATH=. python hfdocs/generate_model_docs.py --families resnet convnext
    PYTHONPATH=. python hfdocs/generate_model_docs.py --check

Adding a family is adding an entry to ``FAMILIES``. A module holding several families can be split with the
``include`` / ``exclude`` architecture name filters (fnmatch patterns, as accepted by ``timm.list_models``).
"""
import argparse
import ast
import copy
import csv
import logging
import math
import re
import sys
import textwrap
import time
import warnings
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import torch

import timm
from timm.models import get_pretrained_cfg
from timm.models._manipulate import group_parameters

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DOCS_SOURCE = _REPO_ROOT / 'hfdocs' / 'source'
_GITHUB_BLOB = 'https://github.com/huggingface/pytorch-image-models/blob/main'
_HUB_URL = 'https://huggingface.co'
_MODEL_API_PAGE = '../model_api'
_MATRIX_BEGIN = '<!-- BEGIN GENERATED SUPPORT MATRIX -->'
_MATRIX_END = '<!-- END GENERATED SUPPORT MATRIX -->'
_GENERATED_NOTE = (
    '<!-- Generated by hfdocs/generate_model_docs.py, do not edit. '
    'Change the FAMILIES entry or the model code / docstring and regenerate. -->'
)

# One entry per family page, keyed by page slug (module name with '_' replaced by '-').
#   title: page title, category: one of CNN, ViT, Hybrid, Efficient/Mobile, MLP, Encoder
#   modules: model modules (``timm/models/<module>.py``) the family is registered in
#   description: short hand written summary, keep it factual and grounded in the module docstring / papers
#   example: (optional) pretrained weight used in the usage snippet, defaults to an automatic pick
#   include / exclude: (optional) architecture name filters to split a module across several pages
FAMILIES: Dict[str, Dict[str, Any]] = {
    'resnet': dict(
        title='ResNet',
        category='CNN',
        modules=('resnet',),
        example='resnet50.a1_in1k',
        description=(
            'Residual networks (ResNet) and the variants built on the same `ResNet` class: ResNeXt grouped '
            'convolutions, Squeeze-and-Excitation (SE) and ECA channel attention, deep / tiered stems and average '
            'pool downsampling (the "c", "d", "s" and "t" variants), anti-aliased downsampling, Wide ResNet and '
            'ResNet-RS configurations.'
        ),
    ),
    'convnext': dict(
        title='ConvNeXt',
        category='CNN',
        modules=('convnext',),
        example='convnext_tiny.in12k_ft_in1k',
        description=(
            'ConvNeXt is a pure convolutional network that adopts design choices from vision transformers, such '
            'as large depthwise kernels, inverted bottlenecks and LayerNorm. ConvNeXt-V2 adds Global Response '
            'Normalization (GRN) and is pretrained as a fully convolutional masked autoencoder (FCMAE).'
        ),
    ),
    'vision-transformer': dict(
        title='Vision Transformer (ViT)',
        category='ViT',
        modules=('vision_transformer',),
        example='vit_base_patch16_224.augreg2_in21k_ft_in1k',
        description=(
            'The Vision Transformer (ViT) splits an image into fixed size patches, linearly embeds them and '
            'processes the resulting token sequence with a standard Transformer encoder. This module holds the '
            '`VisionTransformer` class and the weights for the original ViT, the "How to train your ViT?" '
            '(AugReg) and FlexiViT models, and many image-text (CLIP, SigLIP) and self-supervised '
            'pretrained image towers that share the architecture.'
        ),
    ),
    'efficientnet': dict(
        title='EfficientNet',
        category='Efficient/Mobile',
        modules=('efficientnet',),
        example='efficientnet_b0.ra_in1k',
        description=(
            'EfficientNet and EfficientNetV2, and the related mobile architectures built from the same depthwise '
            'separable, inverted residual (MBConv) and fused MBConv blocks: MixNet, MnasNet, FBNet, Single-Path NAS, '
            'MobileNet-V1 / V2, EfficientNet-Lite, EdgeTPU and TinyNet.'
        ),
    ),
}

# Hosts whose links in a module docstring are taken as paper references (code / weight links are skipped).
_PAPER_HOSTS = (
    'arxiv.org',
    'openreview.net',
    'proceedings.neurips.cc',
    'papers.nips.cc',
    'openaccess.thecvf.com',
    'proceedings.mlr.press',
    'aclanthology.org',
)
_URL_RE = re.compile(r'https?://[^\s<>`\'"()\[\],]+')
_ARXIV_ID_RE = re.compile(r'(\d{4}\.\d{4,5})(v\d+)?')
_BIBTEX_START_RE = re.compile(r'^\s*@\w+\s*\{')
_DELIMITED_TITLE_RE = re.compile(r"`([^`]{4,})`|'([^']{8,})'|\"([^\"]{8,})\"")
_PAPER_PREFIX_RE = re.compile(r'^.*?\bpaper(?:\s+link)?\s*:\s*', re.IGNORECASE)
_LEAD_PHRASE_RE = re.compile(
    r'^(?:as described in|based on paper|a pytorch impl(?:ementation)? of\s*:?|from)(?:\s+|$)', re.IGNORECASE)


# --------------------------------------------------------------------------------------------------------------------
# Paper references from module docstrings


@dataclass
class Paper:
    """A paper reference parsed from a module docstring or a pretrained config."""
    url: str
    title: Optional[str] = None
    key: str = ''


def _paper_key(url: str) -> str:
    """Normalized key used to de-duplicate paper links (arXiv id without version, else the url)."""
    if 'arxiv.org' in url:
        m = _ARXIV_ID_RE.search(url)
        if m:
            return f'arxiv:{m.group(1)}'
    return url.rstrip('/').lower()


def _normalize_paper_url(url: str) -> str:
    """Point arXiv pdf links to the abstract page."""
    url = url.rstrip('.')
    if 'arxiv.org' in url:
        m = _ARXIV_ID_RE.search(url)
        if m:
            return f'https://arxiv.org/abs/{m.group(1)}{m.group(2) or ""}'
    return url


def _is_paper_url(url: str) -> bool:
    host = url.split('/')[2].lower()
    return any(host == h or host.endswith('.' + h) for h in _PAPER_HOSTS)


def _split_bibtex(doc: str) -> Tuple[List[str], List[str]]:
    """Split a docstring into BibTeX entries and the remaining lines."""
    entries = []
    other = []
    lines = doc.splitlines()
    i = 0
    while i < len(lines):
        if _BIBTEX_START_RE.match(lines[i]):
            depth = 0
            block = []
            while i < len(lines):
                block.append(lines[i])
                depth += lines[i].count('{') - lines[i].count('}')
                i += 1
                if depth <= 0:
                    break
            indent = min(len(ln) - len(ln.lstrip()) for ln in block if ln.strip())
            entries.append('\n'.join(ln[indent:] for ln in block).strip())
        else:
            other.append(lines[i])
            i += 1
    return entries, other


def _bibtex_field(entry: str, name: str) -> Optional[str]:
    """Extract a (possibly brace nested) field value from a BibTeX entry."""
    m = re.search(rf'\b{name}\s*=\s*', entry, re.IGNORECASE)
    if not m:
        return None
    rest = entry[m.end():]
    if rest.startswith('{'):
        depth = 0
        for i, c in enumerate(rest):
            depth += (c == '{') - (c == '}')
            if depth == 0:
                value = rest[1:i]
                break
        else:
            return None
    elif rest.startswith('"'):
        end = rest.find('"', 1)
        value = rest[1:end] if end > 0 else ''
    else:
        value = re.split(r'[,\n}]', rest, maxsplit=1)[0]
    return ' '.join(value.replace('{', '').replace('}', '').split()) or None


def _bibtex_paper(entry: str) -> Optional[Paper]:
    """Paper reference for a BibTeX entry, if it carries an arXiv id or url."""
    title = _bibtex_field(entry, 'title')
    url = _bibtex_field(entry, 'url')
    if not url:
        arxiv = None
        for name in ('eprint', 'journal', 'booktitle'):
            value = _bibtex_field(entry, name) or ''
            m = _ARXIV_ID_RE.search(value)
            if m and (name == 'eprint' or 'arxiv' in value.lower()):
                arxiv = m.group(1)
                break
        url = f'https://arxiv.org/abs/{arxiv}' if arxiv else None
    if not url and not title:
        return None
    return Paper(url=url or '', title=title, key=_paper_key(url) if url else f'title:{(title or "").lower()}')


def _clean_title(text: str) -> Optional[str]:
    """Reduce the non-url text of a docstring line to a paper title, or None if nothing title-like remains."""
    m = _DELIMITED_TITLE_RE.search(text)
    if m:
        return next(g for g in m.groups() if g).strip()
    text = re.sub(r'\(\s*\)', ' ', text)
    text = _PAPER_PREFIX_RE.sub('', text)
    text = text.strip().lstrip('*-•').strip()
    text = _LEAD_PHRASE_RE.sub('', text)
    if text.startswith('('):
        return None  # only a remark left, e.g. "paper: <url> (CVPR 2025)"
    text = text.strip(' \t-–:,.')
    if len(text) < 4 or not re.search(r'[A-Za-z]{3}', text):
        return None
    return ' '.join(text.split())


def parse_papers(doc: Optional[str]) -> Tuple[List[Paper], List[str]]:
    """Parse paper references and BibTeX entries from a module docstring.

    Handles the common docstring styles in ``timm/models``: ``* `Title` - url``, ``Paper: Title - url``,
    ``Title (url)``, a title line followed by an indented ``- url`` line, and bare BibTeX blocks. Titles that
    cannot be found in the text are taken from a BibTeX entry with the same arXiv id, if any.

    Args:
        doc: Module docstring.

    Returns:
        Paper references in docstring order (de-duplicated) and the raw BibTeX entries.
    """
    if not doc:
        return [], []
    bibtex, lines = _split_bibtex(doc)
    bib_papers = [p for p in (_bibtex_paper(e) for e in bibtex) if p is not None]
    bib_titles = {p.key: p.title for p in bib_papers if p.title}

    papers: Dict[str, Paper] = {}
    prev_text = ''
    for line in lines:
        urls = _URL_RE.findall(line)
        paper_urls = [u for u in urls if _is_paper_url(u)]
        rest = _URL_RE.sub(' ', line)
        if not paper_urls:
            if line.strip():
                prev_text = rest if not urls else ''
            continue
        title = _clean_title(rest) if len(paper_urls) == 1 else None
        if title is None and len(paper_urls) == 1 and not rest.strip(' \t*-•'):
            # url only line, the title is expected on the line above (e.g. "Paper: `Title`\n    - url")
            title = _clean_title(prev_text)
        for url in paper_urls:
            url = _normalize_paper_url(url)
            key = _paper_key(url)
            delimited = _DELIMITED_TITLE_RE.search(rest) or _DELIMITED_TITLE_RE.search(prev_text)
            if not delimited and key in bib_titles:
                title = bib_titles[key]
            if key not in papers:
                papers[key] = Paper(url=url, title=title, key=key)
            elif title and not papers[key].title:
                papers[key].title = title
        prev_text = ''

    # BibTeX entries without an arXiv id / url: skip if the title is already listed, else attach the titles to
    # the untitled links when they pair up one to one (e.g. "Paper: <url>" followed by a single BibTeX entry).
    def _norm(t: Optional[str]) -> str:
        return re.sub(r'[^a-z0-9]', '', (t or '').lower())

    listed = {_norm(p.title) for p in papers.values() if p.title}
    loose = [p for p in bib_papers if not p.url and _norm(p.title) not in listed]
    untitled = [p for p in papers.values() if not p.title]
    if loose and len(loose) == len(untitled):
        for p, b in zip(untitled, loose):
            p.title = b.title
        loose = []
    for p in bib_papers:
        if p.url and p.key not in papers and _norm(p.title) not in listed:
            papers[p.key] = p
    for p in loose:
        papers[p.key] = p
    return list(papers.values()), bibtex


def config_papers(pretrained_cfgs: Sequence[Any]) -> List[Paper]:
    """Paper references from the ``paper_ids`` / ``paper_name`` fields of pretrained configs."""
    papers: Dict[str, Paper] = {}
    for cfg in pretrained_cfgs:
        if not cfg.paper_ids:
            continue
        for pid in str(cfg.paper_ids).split(','):
            pid = pid.strip()
            m = _ARXIV_ID_RE.search(pid)
            if not m or 'arxiv' not in pid.lower():
                continue
            url = f'https://arxiv.org/abs/{m.group(1)}'
            key = _paper_key(url)
            if key not in papers:
                papers[key] = Paper(url=url, title=cfg.paper_name, key=key)
            elif cfg.paper_name and not papers[key].title:
                papers[key].title = cfg.paper_name
    return list(papers.values())


# --------------------------------------------------------------------------------------------------------------------
# Results / benchmark data


def load_results(path: Path) -> Dict[str, List[Dict[str, str]]]:
    """Load an ImageNet results csv, keyed by full ``arch.tag`` name (one row per evaluated image size)."""
    rows = defaultdict(list)
    if not path.exists():
        return rows
    with open(path, newline='') as f:
        for row in csv.DictReader(f):
            rows[row['model']].append(row)
    return rows


def load_benchmark(
        results_dir: Path,
        architectures: Sequence[str],
        path: Optional[Path] = None,
) -> Tuple[Optional[Path], Dict[Tuple[str, int], Dict[str, str]]]:
    """Load an inference benchmark csv, keyed by ``(arch, img_size)``.

    Params and GMACs do not depend on the benchmark hardware, so when no path is given the csv covering the most
    currently registered architectures is used (the newest benchmark runs cover the most models).
    """
    archs = set(architectures)
    best = None
    if path is None:
        for p in sorted(results_dir.glob('benchmark-infer-*.csv')):
            with open(p, newline='') as f:
                rows = list(csv.DictReader(f))
            if 'infer_gmacs' not in rows[0] or 'param_count' not in rows[0]:
                continue
            coverage = len({r['model'] for r in rows} & archs)
            if best is None or coverage > best[0]:
                best = (coverage, p, rows)
        if best is None:
            return None, {}
        path, rows = best[1], best[2]
    else:
        with open(path, newline='') as f:
            rows = list(csv.DictReader(f))
    return path, {(r['model'], int(r['infer_img_size'])): r for r in rows}


# --------------------------------------------------------------------------------------------------------------------
# Model API capability probe

# (key, label, Model API page anchor), in display order. Anchors are the section slugs of the Model API page.
FEATURES = (
    ('features_only', '`features_only=True` feature maps', 'intermediate-features'),
    ('forward_intermediates', '`forward_intermediates()`', 'intermediate-features'),
    ('prune_intermediate_layers', '`prune_intermediate_layers()`', 'intermediate-features'),
    ('flexible_input', 'Any input size, no changes needed', 'input-size'),
    ('set_input_size', '`set_input_size()`', 'input-size'),
    ('dynamic_img_size', '`dynamic_img_size=True`', 'input-size'),
    ('grad_checkpointing', '`set_grad_checkpointing()`', 'training-hooks'),
    ('group_matcher', 'Layer-wise LR decay (`group_matcher()`)', 'training-hooks'),
    ('reset_classifier', '`reset_classifier()`', 'classifier'),
)
_MATRIX_HEADERS = {
    'features_only': '`features_only`',
    'forward_intermediates': '`forward_intermediates`',
    'prune_intermediate_layers': '`prune_intermediate_layers`',
    'flexible_input': 'Any input size',
    'set_input_size': '`set_input_size`',
    'dynamic_img_size': '`dynamic_img_size`',
    'grad_checkpointing': 'Grad checkpointing',
    'group_matcher': 'Layer decay',
    'reset_classifier': '`reset_classifier`',
}

# Probe outcomes. SQUARE: works for square sizes other than the default but not for a non-square size.
YES, NO, SQUARE, NOT_NEEDED = 'yes', 'no', 'square', 'n/a'
_SYMBOLS = {YES: '✓', NO: '✗', SQUARE: '✓ (square)', NOT_NEEDED: '–'}
_LEGEND = (
    '✓ supported, ✓ (square) works for square sizes only, ✗ not supported, – not needed (the model already accepts '
    'any input size).'
)


@dataclass
class ProbeResult:
    """Model API probe outcome for one model class (probed on one representative architecture)."""
    model_class: str
    arch: str
    img_size: Tuple[int, int]
    status: Dict[str, str] = field(default_factory=dict)
    errors: Dict[str, str] = field(default_factory=dict)
    feature_reductions: List[int] = field(default_factory=list)
    seconds: float = 0.


def _first_tensor(out: Any) -> torch.Tensor:
    if isinstance(out, (tuple, list)):
        out = out[0]
    if isinstance(out, dict):
        out = next(iter(out.values()))
    if not isinstance(out, torch.Tensor):
        raise TypeError(f'unexpected output type {type(out).__name__}')
    return out


def _forward_ok(model: torch.nn.Module, size: Tuple[int, int], batch_size: int = 1) -> None:
    """Run a forward pass, raise if it fails or a classifier output is not ``(batch_size, num_classes)``."""
    out = _first_tensor(model(torch.randn(batch_size, 3, *size)))
    num_classes = getattr(model, 'num_classes', 0)
    if hasattr(model, 'reset_classifier') and num_classes:
        if tuple(out.shape) != (batch_size, num_classes):
            raise ValueError(f'output shape {tuple(out.shape)}, expected {(batch_size, num_classes)}')
    elif out.shape[0] != batch_size:
        raise ValueError(f'output shape {tuple(out.shape)}')


def _size_support(model: torch.nn.Module, square: Tuple[int, int], rect: Tuple[int, int]) -> str:
    """Forward at a non-default square size, then a non-square size. Raise if the square size fails."""
    _forward_ok(model, square)
    try:
        _forward_ok(model, rect)
    except Exception:
        return SQUARE
    return YES


def _err(e: BaseException) -> str:
    return f'{type(e).__name__}: {str(e).splitlines()[0][:200] if str(e) else ""}'


def probe_model_api(arch: str, model_class: str) -> ProbeResult:
    """Functionally probe the model API of a randomly initialized model on CPU.

    Signature or ``hasattr`` checks alone are unreliable (some classes accept and silently drop unknown kwargs, some
    methods exist but assert), so each feature counts only if a small call using it actually works. Probe steps catch
    any exception on purpose, a model failing a feature for any reason means the feature is not usable.

    Args:
        arch: Architecture name, ideally the smallest of its class.
        model_class: Name of the model class, for reporting.

    Returns:
        The probe result.
    """
    t0 = time.perf_counter()
    cfg = get_pretrained_cfg(arch)
    h, w = cfg.input_size[-2:]
    res = ProbeResult(model_class=model_class, arch=arch, img_size=(h, w))
    status, errors = res.status, res.errors

    torch.manual_seed(0)
    base = timm.create_model(arch, pretrained=False).eval()
    with torch.no_grad():
        _forward_ok(base, (h, w))  # must work, anything below is meaningless otherwise

    # A size step that is a multiple of the network stride (or patch size), at least 32 px.
    stride = 32
    feature_info = getattr(base, 'feature_info', None)
    if isinstance(feature_info, (list, tuple)) and feature_info and feature_info[-1].get('reduction'):
        stride = int(feature_info[-1]['reduction'])
    step = stride * math.ceil(32 / stride)
    square, rect = (h + step, w + step), (h + step, w + 2 * step)

    def _check(key: str, fn) -> None:
        try:
            with torch.no_grad():
                status[key] = fn()
        except Exception as e:
            status[key] = NO
            errors[key] = _err(e)

    _check('flexible_input', lambda: _size_support(base, square, rect))
    flexible = status['flexible_input'] != NO

    def _features_only():
        model = timm.create_model(arch, pretrained=False, features_only=True).eval()
        feats = model(torch.randn(1, 3, h, w))
        reductions = [int(r) for r in model.feature_info.reduction()]  # for the selected out_indices
        if not isinstance(feats, (list, tuple)) or not feats or len(feats) != len(reductions):
            raise ValueError('unexpected feature output')
        res.feature_reductions = reductions
        return YES
    _check('features_only', _features_only)

    def _forward_intermediates():
        feats = base.forward_intermediates(torch.randn(1, 3, h, w), intermediates_only=True)
        if not isinstance(feats, (list, tuple)) or not feats or not all(isinstance(f, torch.Tensor) for f in feats):
            raise ValueError('unexpected intermediates output')
        return YES
    _check('forward_intermediates', _forward_intermediates)

    def _prune():
        model = copy.deepcopy(base)
        num_params = sum(p.numel() for p in model.parameters())
        model.prune_intermediate_layers(indices=[0], prune_norm=True, prune_head=True)
        feats = model.forward_intermediates(torch.randn(1, 3, h, w), indices=[0], intermediates_only=True)
        if len(feats) != 1:
            raise ValueError(f'{len(feats)} intermediates after pruning to one')
        if sum(p.numel() for p in model.parameters()) >= num_params:
            raise ValueError('no parameters removed')
        return YES
    _check('prune_intermediate_layers', _prune)

    def _set_input_size():
        if not hasattr(base, 'set_input_size'):
            if flexible:
                return NOT_NEEDED
            raise AttributeError('no set_input_size()')
        try:
            model = copy.deepcopy(base)
            model.set_input_size(img_size=rect)
            _forward_ok(model, rect)
            return YES
        except Exception:
            model = copy.deepcopy(base)
            model.set_input_size(img_size=square)
            _forward_ok(model, square)
            return SQUARE
    _check('set_input_size', _set_input_size)

    def _dynamic_img_size():
        try:
            model = timm.create_model(arch, pretrained=False, dynamic_img_size=True).eval()
            enabled = any(getattr(m, 'dynamic_img_size', None) is True for m in model.modules())
            if not enabled:
                raise ValueError('dynamic_img_size=True accepted but not enabled')
        except Exception:
            if flexible:
                return NOT_NEEDED
            raise
        return _size_support(model, square, rect)
    _check('dynamic_img_size', _dynamic_img_size)

    def _group_matcher():
        layer_map = group_parameters(base, base.group_matcher(coarse=False), reverse=True)
        if len(set(layer_map.values())) < 2:
            raise ValueError('all parameters in one group')
        return YES
    _check('group_matcher', _group_matcher)

    def _grad_checkpointing():
        # Checkpointed segments are re-run during backward, count module forward calls to see that it happens.
        model = copy.deepcopy(base).train()
        model.set_grad_checkpointing(True)
        calls = [0]

        def _hook(*args):
            calls[0] += 1

        handles = [m.register_forward_hook(_hook) for m in model.modules()]
        try:
            with torch.enable_grad():
                out = model(torch.randn(2, 3, h, w))
                outs = out if isinstance(out, (tuple, list)) else (out,)
                loss = sum(o.float().mean() for o in outs if isinstance(o, torch.Tensor))
                forward_calls = calls[0]
                loss.backward()
        finally:
            for handle in handles:
                handle.remove()
        if calls[0] == forward_calls:
            raise ValueError('set_grad_checkpointing(True) accepted but nothing is recomputed in backward')
        return YES
    _check('grad_checkpointing', _grad_checkpointing)

    def _reset_classifier():
        model = copy.deepcopy(base)
        model.reset_classifier(7)
        _forward_ok(model, (h, w))
        if model.num_classes != 7:
            raise ValueError('num_classes not updated')
        model.reset_classifier(0)
        out = _first_tensor(model(torch.randn(1, 3, h, w)))
        if out.ndim != 2:
            raise ValueError(f'reset_classifier(0) output shape {tuple(out.shape)}')
        return YES
    _check('reset_classifier', _reset_classifier)

    res.seconds = time.perf_counter() - t0
    return res


# --------------------------------------------------------------------------------------------------------------------
# Family data


@dataclass
class ArchInfo:
    """Registered architecture of a family."""
    name: str
    model_class: str
    params_m: Optional[float]
    gmacs: Optional[str]
    input_size: Tuple[int, int]
    num_pretrained: int


@dataclass
class FamilyData:
    """Everything needed to render a family page."""
    slug: str
    spec: Dict[str, Any]
    archs: List[ArchInfo]
    weights: List[str]
    papers: List[Paper]
    weight_papers: List[Paper]
    bibtex: List[str]
    probes: Dict[str, ProbeResult]
    example: Optional[str]
    issues: List[str]


def _fmt_size(size: Sequence[int]) -> str:
    h, w = size[-2:]
    return str(h) if h == w else f'{h}x{w}'


def collect_family(
        slug: str,
        spec: Dict[str, Any],
        results: Dict[str, List[Dict[str, str]]],
        benchmark: Dict[Tuple[str, int], Dict[str, str]],
        probe: bool = True,
        log=print,
) -> FamilyData:
    """Gather the registry, results, docstring and probe data for one family."""
    issues = []
    filters = dict(
        filter=spec.get('include', ''),
        module=list(spec['modules']),
        exclude_filters=spec.get('exclude', ''),
    )
    arch_names = timm.list_models(**filters)
    arch_order = {name: i for i, name in enumerate(arch_names)}
    weights = sorted(timm.list_models(pretrained=True, **filters), key=lambda w: (arch_order[w.split('.')[0]], w))
    if not arch_names:
        raise ValueError(f'family {slug}: no architectures registered for {spec["modules"]}')

    num_pretrained = defaultdict(int)
    for w in weights:
        num_pretrained[w.split('.')[0]] += 1

    archs = []
    by_class = defaultdict(list)
    for name in arch_names:
        # Construction on the meta device is cheap, gives the model class and a param count fallback.
        with warnings.catch_warnings(), torch.device('meta'):
            warnings.simplefilter('ignore')
            model = timm.create_model(name, pretrained=False)
        model_class = type(model).__name__
        meta_params = sum(p.numel() for p in model.parameters()) / 1e6
        del model
        by_class[model_class].append((meta_params, name))

        input_size = tuple(get_pretrained_cfg(name).input_size[-2:])
        bench = benchmark.get((name, input_size[-1])) if input_size[0] == input_size[1] else None
        params_m = float(bench['param_count']) if bench else round(meta_params, 2)
        if bench and abs(float(bench['param_count']) - meta_params) > max(0.01, 0.005 * meta_params):
            issues.append(f'{name}: benchmark param_count {bench["param_count"]}M, current code {meta_params:.2f}M')
        if not bench:
            issues.append(f'{name}: no benchmark row at img_size {_fmt_size(input_size)}')
        archs.append(ArchInfo(
            name=name,
            model_class=model_class,
            params_m=params_m,
            gmacs=f'{float(bench["infer_gmacs"]):.2f}' if bench else None,
            input_size=input_size,
            num_pretrained=num_pretrained[name],
        ))

    papers, bibtex = [], []
    for module in spec['modules']:
        source = (_REPO_ROOT / 'timm' / 'models' / f'{module}.py').read_text()
        p, b = parse_papers(ast.get_docstring(ast.parse(source)))
        papers += p
        bibtex += b
    seen = {p.key for p in papers}
    weight_papers = [p for p in config_papers([get_pretrained_cfg(w) for w in weights]) if p.key not in seen]
    if not papers:
        issues.append(f'no paper references parsed from the docstring of {", ".join(spec["modules"])}')

    for w in weights:
        if not get_pretrained_cfg(w).hf_hub_id:
            issues.append(f'{w}: no hf_hub_id')

    probes = {}
    if probe:
        for model_class, entries in sorted(by_class.items()):
            # Smallest architecture of the class, test_* models are skipped as they use deliberately unusual
            # configs (e.g. test_vit enables dynamic_img_size) unless the class has nothing else.
            arch = min([e for e in entries if not e[1].startswith('test_')] or entries)[1]
            try:
                probes[model_class] = probe_model_api(arch, model_class)
            except Exception as e:
                issues.append(f'probe of {model_class} ({arch}) failed: {_err(e)}')
                continue
            r = probes[model_class]
            log(f'  probed {model_class} with {arch} in {r.seconds:.1f}s')
            for key, err in r.errors.items():
                log(f'    {key}: {err}')

    example = spec.get('example')
    if example and example not in weights:
        issues.append(f'example weight {example} is not a pretrained tag of this family')
        example = None
    if not example:
        example = _pick_example(archs, weights, results)

    return FamilyData(
        slug=slug,
        spec=spec,
        archs=archs,
        weights=weights,
        papers=papers,
        weight_papers=weight_papers,
        bibtex=bibtex,
        probes=probes,
        example=example,
        issues=issues,
    )


def _pick_example(archs: Sequence[ArchInfo], weights: Sequence[str], results: Dict[str, List]) -> Optional[str]:
    """Default usage example: the ImageNet-1k weight closest to 25M params (a typical base size), not a test model."""
    candidates = []
    params = {a.name: a.params_m for a in archs}
    for w in weights:
        arch = w.split('.')[0]
        if arch.startswith('test_') or w not in results or params.get(arch) is None:
            continue
        candidates.append((abs(math.log(params[arch] / 25.)), w))
    return min(candidates)[1] if candidates else (weights[0] if weights else None)


def _top1(name: str, results: Dict[str, List[Dict[str, str]]]) -> Optional[Dict[str, str]]:
    """Results row for a weight at its pretrained config test size (else input size), else its best row."""
    rows = results.get(name)
    if not rows:
        return None
    cfg = get_pretrained_cfg(name)
    eval_size = (cfg.test_input_size or cfg.input_size)[-1]
    for row in rows:
        if int(row['img_size']) == eval_size:
            return row
    return max(rows, key=lambda r: float(r['top1']))


# --------------------------------------------------------------------------------------------------------------------
# Rendering


def _md(text: str) -> str:
    """Escape text for a markdown table cell / MDX prose."""
    return text.replace('|', '\\|').replace('<', '&lt;').replace('{', '&#123;').replace('}', '&#125;')


def _table(headers: Sequence[str], rows: Sequence[Sequence[str]], align: Optional[Sequence[str]] = None) -> str:
    align = align or ['l'] * len(headers)
    sep = ['---:' if a == 'r' else '---' for a in align]
    lines = ['| ' + ' | '.join(headers) + ' |', '|' + '|'.join(sep) + '|']
    lines += ['| ' + ' | '.join(r) + ' |' for r in rows]
    return '\n'.join(lines)


def _feature_cell(r: ProbeResult, key: str) -> str:
    value = r.status.get(key, NO)
    cell = _SYMBOLS[value]
    if key == 'features_only' and value == YES and r.feature_reductions:
        cell += ' (strides ' + ', '.join(str(x) for x in r.feature_reductions) + ')'
    return cell


def render_family(data: FamilyData, results: Dict[str, List[Dict[str, str]]]) -> str:
    """Render the MDX page of a family."""
    spec = data.spec
    modules = spec['modules']
    module_links = ', '.join(f'[`timm/models/{m}.py`]({_GITHUB_BLOB}/timm/models/{m}.py)' for m in modules)
    num_in1k = sum(1 for w in data.weights if w in results)
    out = [
        _GENERATED_NOTE,
        '',
        f'# {spec["title"]}',
        '',
        f'**Category:** {spec["category"]} · **Code:** {module_links} · **Architectures:** {len(data.archs)} · '
        f'**Pretrained weights:** {len(data.weights)} ({num_in1k} with ImageNet-1k results)',
        '',
        spec['description'],
        '',
    ]

    def _paper_item(p: Paper) -> str:
        title = _md(p.title) if p.title else p.key.replace('arxiv:', 'arXiv:')
        return f'* [{title}]({p.url})' if p.url else f'* {title}'

    out += ['## Papers', '']
    if data.papers:
        out += [_paper_item(p) for p in data.papers]
    else:
        out.append('The module docstring does not reference any papers.')
    if data.weight_papers:
        out += ['', 'Referenced by pretrained weights:', '']
        out += [_paper_item(p) for p in data.weight_papers]
    out.append('')

    out += [
        '## Usage',
        '',
        'See the [Quickstart](../quickstart) for loading pretrained weights, image preprocessing and fine-tuning, '
        'and [Feature Extraction](../feature_extraction) for using the models as backbones.',
        '',
    ]
    if data.example:
        out += [
            '```py',
            '>>> import timm',
            f">>> model = timm.create_model('{data.example}', pretrained=True)",
            '>>> data_config = timm.data.resolve_model_data_config(model)',
            '```',
            '',
        ]

    out += ['## Model API support', '']
    if data.probes:
        classes = sorted(data.probes)
        headers = ['Feature'] + [f'`{c}`' for c in classes]
        rows = []
        for key, label, anchor in FEATURES:
            link = f'[{label}]({_MODEL_API_PAGE}#{anchor})'
            rows.append([link] + [_feature_cell(data.probes[c], key) for c in classes])
        out += [_table(headers, rows), '']
        probed = ', '.join(
            f'`{c}` with `{data.probes[c].arch}` at {_fmt_size(data.probes[c].img_size)}' for c in classes)
        out += [
            f'{_LEGEND} Checked by running each feature on a randomly initialized model ({probed}), other '
            f'architectures of the same class are expected to behave the same. See the '
            f'[Model API]({_MODEL_API_PAGE}) page for details.',
            '',
        ]
    else:
        out += ['Not probed.', '']

    out += ['## Architectures', '']
    multi_class = len({a.model_class for a in data.archs}) > 1
    headers = ['Architecture'] + (['Class'] if multi_class else []) + [
        'Params (M)', 'GMACs', 'Input size', 'Pretrained weights']
    align = ['l'] + (['l'] if multi_class else []) + ['r', 'r', 'r', 'r']
    rows = []
    for a in data.archs:
        rows.append([f'`{a.name}`'] + ([f'`{a.model_class}`'] if multi_class else []) + [
            f'{a.params_m:.2f}' if a.params_m is not None else '-',
            a.gmacs or '-',
            _fmt_size(a.input_size),
            str(a.num_pretrained),
        ])
    out += [
        _table(headers, rows, align),
        '',
        'GMACs and parameter counts are for the default input size and classifier of each architecture, from the '
        '[benchmark results](https://github.com/huggingface/pytorch-image-models/tree/main/results).',
        '',
    ]

    out += ['## Pretrained weights', '']
    rows = []
    for w in data.weights:
        cfg = get_pretrained_cfg(w)
        row = _top1(w, results)
        if cfg.hf_hub_id:
            hub_text = 'timm' if cfg.hf_hub_id == f'timm/{w}' else cfg.hf_hub_id
            hub = f'[{_md(hub_text)}]({_HUB_URL}/{cfg.hf_hub_id})'
        elif cfg.url:
            hub = f'[original]({cfg.url})'
        else:
            hub = '-'
        input_size = _fmt_size(cfg.input_size)
        if cfg.test_input_size and tuple(cfg.test_input_size) != tuple(cfg.input_size):
            input_size += f' (test {_fmt_size(cfg.test_input_size)})'
        rows.append([
            f'`{w}`',
            input_size,
            row['top1'] if row else '-',
            row['img_size'] if row else '-',
            str(cfg.num_classes) if cfg.num_classes else 'none',
            _md(cfg.license or '-'),
            hub,
        ])
    out += [
        _table(['Weight', 'Input size', 'Top-1 (%)', 'Eval size', 'Classes', 'License', 'Hub'], rows,
               ['l', 'r', 'r', 'r', 'r', 'l', 'l']),
        '',
        'Top-1 is ImageNet-1k validation accuracy from [`results-imagenet.csv`]'
        '(https://github.com/huggingface/pytorch-image-models/blob/main/results/results-imagenet.csv) at the '
        'listed eval size, - if the weight has no ImageNet-1k result (e.g. pretraining or image-text weights). '
        'Classes is the size of the pretrained classifier, none for weights without one.',
        '',
    ]

    if data.bibtex:
        out += ['## Citation', '', '```bibtex', '\n\n'.join(data.bibtex), '```', '']
    return '\n'.join(out)


def render_support_matrix(families: Sequence[FamilyData]) -> str:
    """Render the Model API support matrix (one row per family and model class)."""
    keys = [k for k, _, _ in FEATURES]
    headers = ['Family', 'Class'] + [_MATRIX_HEADERS[k] for k in keys]
    rows = []
    for data in families:
        for c in sorted(data.probes):
            r = data.probes[c]
            rows.append([f'[{_md(data.spec["title"])}](models/{data.slug})', f'`{c}`'] + [
                _SYMBOLS[r.status.get(k, NO)] for k in keys])
    return '\n'.join([
        _GENERATED_NOTE,
        '',
        _table(headers, rows),
        '',
        f'{_LEGEND} Each class is checked by running every feature on a randomly initialized model of '
        'its smallest (non-test) architecture.',
        '',
    ])


def splice_matrix(page: Path, matrix: str) -> Optional[str]:
    """Return ``page`` with ``matrix`` between the generated support matrix markers, or None if not applicable."""
    if not page.exists():
        return None
    text = page.read_text()
    begin, end = text.find(_MATRIX_BEGIN), text.find(_MATRIX_END)
    if begin < 0 or end < begin:
        return None
    return text[:begin + len(_MATRIX_BEGIN)] + '\n' + matrix + text[end:]


# --------------------------------------------------------------------------------------------------------------------


def wrap_markdown(text: str, width: int = 120) -> str:
    """Wrap prose and list item lines of generated markdown to the docs line length.

    Tables, headings, code blocks and lines that are already short enough are left as is. Inline code and links are
    never split.

    Args:
        text: Markdown text.
        width: Maximum line length.

    Returns:
        The wrapped text.
    """
    out = []
    in_code = False
    for line in text.split('\n'):
        if line.lstrip().startswith('```'):
            in_code = not in_code
            out.append(line)
            continue
        if in_code or len(line) <= width or line.lstrip().startswith(('|', '#')):
            out.append(line)
            continue
        stripped = line.lstrip()
        indent = line[:len(line) - len(stripped)]
        bullet = re.match(r'([-*] |\d+\. )', stripped)
        subsequent = indent + ' ' * (len(bullet.group(1)) if bullet else 0)
        out.append(textwrap.fill(
            stripped,
            width=width,
            initial_indent=indent,
            subsequent_indent=subsequent,
            break_long_words=False,
            break_on_hyphens=False,
        ))
    return '\n'.join(out)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument(
        '--families', nargs='+', default=None, choices=sorted(FAMILIES), metavar='SLUG',
        help='families to generate, default all. The support matrix is only updated when all are generated')
    parser.add_argument('--output-dir', type=Path, default=_DOCS_SOURCE / 'models', help='family page directory')
    parser.add_argument('--results-dir', type=Path, default=_REPO_ROOT / 'results', help='results csv directory')
    parser.add_argument('--benchmark-csv', type=Path, default=None, help='benchmark csv for params / GMACs')
    parser.add_argument(
        '--matrix-file', type=Path, default=None,
        help='also write the support matrix to this file')
    parser.add_argument(
        '--model-api-page', type=Path, default=_DOCS_SOURCE / 'model_api.mdx',
        help='page to splice the support matrix into, if it has the generated support matrix markers')
    parser.add_argument('--no-probe', action='store_true', help='skip the model API probe (no support tables)')
    parser.add_argument('--check', action='store_true', help='do not write, exit 1 if any output is out of date')
    parser.add_argument('-v', '--verbose', action='store_true', help='print data issues')
    args = parser.parse_args(argv)

    if _REPO_ROOT not in Path(timm.__file__).resolve().parents:
        print(f'timm imported from {timm.__file__}, not this repository. Run with PYTHONPATH={_REPO_ROOT}.',
              file=sys.stderr)
        return 2
    logging.getLogger('timm').setLevel(logging.ERROR)
    warnings.filterwarnings('ignore')
    torch.set_grad_enabled(True)

    t0 = time.perf_counter()
    slugs = args.families or list(FAMILIES)
    results = load_results(args.results_dir / 'results-imagenet.csv')
    bench_path, benchmark = load_benchmark(args.results_dir, timm.list_models(), args.benchmark_csv)
    print(f'timm {timm.__version__} from {Path(timm.__file__).parent}, benchmark data {bench_path}')

    families = []
    outputs: Dict[Path, str] = {}
    for slug in slugs:
        print(f'{slug}:')
        data = collect_family(slug, FAMILIES[slug], results, benchmark, probe=not args.no_probe)
        families.append(data)
        outputs[args.output_dir / f'{slug}.mdx'] = render_family(data, results)
        print(f'  {len(data.archs)} architectures, {len(data.weights)} weights, {len(data.papers)} papers, '
              f'{len(data.issues)} data issues')
        if args.verbose:
            for issue in data.issues:
                print(f'    {issue}')

    if args.no_probe or set(slugs) != set(FAMILIES):
        # the matrix covers every family, a partial run would drop rows
        print('support matrix not updated (needs all families and the probe)')
    else:
        matrix = render_support_matrix(families)
        if args.matrix_file is not None:
            outputs[args.matrix_file] = matrix
        spliced = splice_matrix(args.model_api_page, matrix)
        if spliced is not None:
            outputs[args.model_api_page] = spliced

    stale = []
    for path, text in outputs.items():
        text = wrap_markdown(text)
        if path.exists() and path.read_text() == text:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    action = 'out of date' if args.check else 'written'
    for path in stale:
        print(f'{action}: {path}')
    print(f'done in {time.perf_counter() - t0:.1f}s')
    return 1 if args.check and stale else 0


if __name__ == '__main__':
    sys.exit(main())
