#!/usr/bin/env python3
"""Generate the per family model pages of the timm docs from code and result data.

Each family page (``hfdocs/source/models/<slug>.mdx``) is built from:
  * a short hand written entry in ``FAMILIES`` below (title, category, 1-3 sentence description),
  * the model module docstring (paper references, BibTeX),
  * the model registry and pretrained configs (architectures, weights, licenses, Hub ids),
  * ``results/results-imagenet.csv`` (ImageNet-1k top-1) and a ``results/benchmark-infer-*.csv`` (params, GMACs),
  * a functional probe of the model API on a randomly initialized, smallest architecture per model class.

The probe results are also rendered as a support matrix (one row per family) and spliced into
``hfdocs/source/model_api.mdx`` between the ``<!-- BEGIN GENERATED SUPPORT MATRIX -->`` /
``<!-- END GENERATED SUPPORT MATRIX -->`` markers, and optionally written to ``--matrix-file``. The families are listed
by category on the ``hfdocs/source/models.mdx`` index page.

Run from the repository root, against the repository timm (not an installed release), offline:

    PYTHONPATH=. python hfdocs/generate_model_docs.py
    PYTHONPATH=. python hfdocs/generate_model_docs.py --families resnet convnext
    PYTHONPATH=. python hfdocs/generate_model_docs.py --check

Every module of ``timm.models.list_modules()`` needs an entry in ``FAMILIES``, a missing one is reported. A module
holding several families can be split with the ``include`` / ``exclude`` architecture name filters (fnmatch
patterns, as accepted by ``timm.list_models``).
"""
import argparse
import ast
import copy
import csv
import logging
import math
import re
import sys
import textwrap
import time
import warnings
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import torch

import timm
from timm.models import get_pretrained_cfg, list_modules
from timm.models._manipulate import group_parameters

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DOCS_SOURCE = _REPO_ROOT / 'hfdocs' / 'source'
_GITHUB_BLOB = 'https://github.com/huggingface/pytorch-image-models/blob/main'
_HUB_URL = 'https://huggingface.co'
_MODEL_API_PAGE = '../model_api'
_MATRIX_BEGIN = '<!-- BEGIN GENERATED SUPPORT MATRIX -->'
_MATRIX_END = '<!-- END GENERATED SUPPORT MATRIX -->'
_GENERATED_NOTE = (
    '<!-- Generated by hfdocs/generate_model_docs.py, do not edit. '
    'Change the FAMILIES entry or the model code / docstring and regenerate. -->'
)

# One entry per family page, keyed by page slug (module name with '_' replaced by '-').
#   title: page title
#   category: one of the CATEGORIES keys
#   description: short hand written summary, keep it factual and grounded in the module docstring / papers
#   modules: (optional) model modules (``timm/models/<module>.py``) the family is registered in, defaults to the
#       module named by the slug
#   example: (optional) pretrained weight used in the usage snippet, defaults to an automatic pick
#   include / exclude: (optional) architecture name filters to split a module across several pages
# Family categories and their index page section titles, in page order.
CATEGORIES = {
    'CNN': 'Convolutional networks',
    'ViT': 'Vision Transformers',
    'Hybrid': 'Hybrid convolution / attention networks',
    'Efficient/Mobile': 'Efficient and mobile networks',
    'MLP': 'MLP and other token mixers',
    'Encoder': 'Multimodal model vision encoders',
}
FAMILIES: Dict[str, Dict[str, Any]] = {
    'beit': dict(
        title='BEiT',
        category='ViT',
        description=(
            'BEiT and BEiT-v2 Vision Transformers, pretrained with masked image modeling. BEiT predicts the discrete '
            'visual tokens of masked patches, BEiT-v2 uses a vector-quantized visual tokenizer for the targets. The '
            'weights here are fine-tuned classification weights.'
        ),
    ),
    'byoanet': dict(
        title='BYOANet (BoTNet, HaloNet, LambdaNet)',
        category='Hybrid',
        description=(
            'Networks built with the `ByobNet` block / stage config system that place self-attention (or similar) '
            'layers in ResNet style stages: Bottleneck Transformers (BoTNet), HaloNets and Lambda ResNets. The '
            'module docstring marks these definitions as experimental.'
        ),
    ),
    'byobnet': dict(
        title='BYOBNet (GENet, RepVGG, MobileOne, ...)',
        category='CNN',
        description=(
            'Bring-Your-Own-Blocks Network, a flexible network built from dataclass configs that stack blocks into '
            'stages. It implements GPU-Efficient Networks (`gernet_*`), RepVGG, MobileOne, RegNetZ, the ResNet image '
            'towers of CLIP (`*_clip`) and a number of ResNet style `timm` variants.'
        ),
    ),
    'cait': dict(
        title='CaiT',
        category='ViT',
        description=(
            'Class-Attention in Image Transformers (CaiT), deep Vision Transformers that use LayerScale and finish '
            'with class-attention layers, which update only the class token from the patch tokens.'
        ),
    ),
    'coat': dict(
        title='CoaT',
        category='Hybrid',
        description=(
            'Co-Scale Conv-Attentional Image Transformers (CoaT) use factorized attention with convolution based '
            'relative position encodings, and a co-scale mechanism that exchanges information between parallel '
            'blocks at different scales.'
        ),
    ),
    'convit': dict(
        title='ConViT',
        category='ViT',
        description=(
            'ConViT replaces the self-attention of the early Vision Transformer blocks with gated positional '
            'self-attention (GPSA), which can be initialized to behave like a convolution, as a soft convolutional '
            'inductive bias.'
        ),
    ),
    'convmixer': dict(
        title='ConvMixer',
        category='CNN',
        description=(
            'ConvMixer embeds the image as patches and keeps that resolution throughout, alternating depthwise '
            'convolutions (spatial mixing) and pointwise convolutions (channel mixing).'
        ),
    ),
    'convnext': dict(
        title='ConvNeXt',
        category='CNN',
        example='convnext_tiny.in12k_ft_in1k',
        description=(
            'ConvNeXt is a pure convolutional network that adopts design choices from vision transformers, such '
            'as large depthwise kernels, inverted bottlenecks and LayerNorm. ConvNeXt-V2 adds Global Response '
            'Normalization (GRN) and is pretrained as a fully convolutional masked autoencoder (FCMAE).'
        ),
    ),
    'cpubone': dict(
        title='CPUBone',
        category='Efficient/Mobile',
        description=(
            'CPUBone is a vision backbone designed for devices with low parallelization capabilities, such as CPUs, '
            'built from (fused) MBConv blocks and convolutional attention blocks.'
        ),
    ),
    'crossvit': dict(
        title='CrossViT',
        category='ViT',
        description=(
            'CrossViT processes small and large image patches in two Transformer branches and fuses them with '
            'cross-attention through the class tokens. Model names in `timm` give the actual input resolution '
            '(240 / 408 instead of the original 224 / 384).'
        ),
    ),
    'csatv2': dict(
        title='CSATv2',
        category='Hybrid',
        description=(
            'CSATv2 is a frequency-domain vision model that works on DCT transforms of the input image, with spatial '
            'attention.'
        ),
    ),
    'cspnet': dict(
        title='CSPNet (CSPResNet, CSPDarkNet, DarkNet)',
        category='CNN',
        description=(
            'Cross Stage Partial Networks split the features of each stage into two parts, one passing through the '
            'stage blocks and one merged back at the end of the stage. This module holds CSPResNet, CSPResNeXt, '
            'CSPDarkNet, DarkNet and the `timm` `cs3*` variants.'
        ),
    ),
    'cspnext': dict(
        title='CSPNeXt',
        category='CNN',
        description=(
            'The CSPNeXt backbone of the RTMDet real-time object detector (CSP blocks with 5x5 depthwise '
            'convolutions), with ImageNet-1k classification weights converted from the OpenMMLab checkpoints.'
        ),
    ),
    'davit': dict(
        title='DaViT',
        category='ViT',
        description=(
            'Dual Attention Vision Transformers (DaViT) combine spatial window attention and channel group '
            'attention, both linear in the number of tokens, in a hierarchical design.'
        ),
    ),
    'deepseek-vit': dict(
        title='DeepSeek ViT',
        category='Encoder',
        description=(
            'The vision encoder of the DeepSeek-V4 / V4.1 multimodal models, a pre-norm ViT with RMSNorm, a SwiGLU '
            'MLP and axial 2D RoPE as the only position encoding. Classifier variants add pooling and a linear head, '
            'the `_enc` variants keep the native projector that maps the tokens to the language model width.'
        ),
    ),
    'deit': dict(
        title='DeiT',
        category='ViT',
        description=(
            'Data-efficient Image Transformers (DeiT) are Vision Transformers trained on ImageNet-1k only, '
            'optionally with a distillation token that learns from a CNN teacher. DeiT III models are trained with '
            'an improved recipe.'
        ),
    ),
    'densenet': dict(
        title='DenseNet',
        category='CNN',
        description=(
            'Densely connected convolutional networks, where each layer in a dense block takes the concatenated '
            'outputs of all preceding layers of the block. Adapted from torchvision, `densenetblur` uses blur pool '
            'anti-aliased downsampling.'
        ),
    ),
    'dla': dict(
        title='DLA',
        category='CNN',
        description=(
            'Deep Layer Aggregation (DLA) networks merge features across blocks and stages with iterative and '
            'hierarchical aggregation nodes. Includes DLA variants built from Res2Net blocks.'
        ),
    ),
    'dpn': dict(
        title='DPN',
        category='CNN',
        description=(
            'Dual Path Networks combine a residual path (feature re-use) and a densely connected path (new feature '
            'exploration) in each block. Compatible with the weights of the original MXNet implementation.'
        ),
    ),
    'edgenext': dict(
        title='EdgeNeXt',
        category='Efficient/Mobile',
        description=(
            'EdgeNeXt is a hybrid CNN-Transformer for mobile devices that combines depthwise convolution encoders '
            'with split depth-wise transpose attention (SDTA) encoders, which apply attention across channels.'
        ),
    ),
    'efficientformer': dict(
        title='EfficientFormer',
        category='Efficient/Mobile',
        description=(
            'EfficientFormer is a vision transformer designed for mobile latency, with pooling based blocks on 4D '
            'feature maps in the early stages and multi-head self-attention blocks in the last stage.'
        ),
    ),
    'efficientformer-v2': dict(
        title='EfficientFormer-V2',
        category='Efficient/Mobile',
        description=(
            'EfficientFormer-V2 revisits the EfficientFormer design to reduce both parameter count and latency for '
            'mobile devices, with convolutional stages and attention in the later, lower resolution stages.'
        ),
    ),
    'efficientnet': dict(
        title='EfficientNet',
        category='Efficient/Mobile',
        example='efficientnet_b0.ra_in1k',
        description=(
            'EfficientNet and EfficientNetV2, and the related mobile architectures built from the same depthwise '
            'separable, inverted residual (MBConv) and fused MBConv blocks: MixNet, MnasNet, FBNet, Single-Path NAS, '
            'MobileNet-V1 / V2, EfficientNet-Lite, EdgeTPU and TinyNet.'
        ),
    ),
    'efficientvim': dict(
        title='EfficientViM',
        category='Efficient/Mobile',
        description=(
            'Efficient Vision Mamba (EfficientViM) is built around the Hidden State Mixer based State Space Duality '
            '(HSM-SSD) layer, implemented here in plain PyTorch. The `_dist` models add a distillation head.'
        ),
    ),
    'efficientvit-mit': dict(
        title='EfficientViT (MIT)',
        category='Efficient/Mobile',
        description=(
            'EfficientViT from the MIT Han Lab, a vision backbone for high-resolution, low-computation recognition '
            'that uses multi-scale linear attention.'
        ),
    ),
    'efficientvit-msra': dict(
        title='EfficientViT (MSRA)',
        category='Efficient/Mobile',
        description=(
            'EfficientViT from Microsoft Research, a memory efficient vision transformer with cascaded group '
            'attention, which feeds each attention head a different split of the features.'
        ),
    ),
    'eva': dict(
        title='EVA',
        category='ViT',
        description=(
            'EVA and EVA-02 Vision Transformers and other ViT variants sharing the `Eva` class, with rotary position '
            'embeddings (RoPE), SwiGLU MLPs and related additions. The module also holds the Perception Encoder (PE), '
            'ROPE-ViT, DINOv3, LingBot-Vision and Sapiens2 models and `timm` original ViT configs with RoPE.'
        ),
    ),
    'fasternet': dict(
        title='FasterNet',
        category='Efficient/Mobile',
        description=(
            'FasterNet is built around partial convolution (PConv), which convolves only a part of the input '
            'channels to reduce redundant computation and memory access.'
        ),
    ),
    'fastvit': dict(
        title='FastViT',
        category='Efficient/Mobile',
        description=(
            'FastViT is a hybrid convolutional / transformer network that uses structural reparameterization to '
            'remove skip connections at inference. The module also includes the MobileCLIP image encoders '
            '(`fastvit_mci*`).'
        ),
    ),
    'focalnet': dict(
        title='FocalNet',
        category='Hybrid',
        description=(
            'Focal Modulation Networks (FocalNet) replace self-attention with focal modulation, which aggregates '
            'context at several granularities with depthwise convolutions and gates it into each query token.'
        ),
    ),
    'gcvit': dict(
        title='GCViT',
        category='ViT',
        description=(
            'Global Context Vision Transformers (GCViT) alternate local window attention with global context '
            'attention, whose queries are generated from the whole feature map by a convolutional module.'
        ),
    ),
    'gemma4-vit': dict(
        title='Gemma 4 ViT',
        category='Encoder',
        description=(
            "The vision encoder of Google's Gemma 4 multimodal models, a ViT with 2D RoPE, gated MLPs, QK "
            'normalization and sandwich normalization blocks.'
        ),
    ),
    'ghostnet': dict(
        title='GhostNet',
        category='Efficient/Mobile',
        description=(
            'GhostNet generates part of its feature maps with cheap operations (Ghost modules). GhostNetV2 adds '
            'DFC attention for long-range dependencies, GhostNetV3 uses re-parameterization and knowledge '
            'distillation in training.'
        ),
    ),
    'hardcorenas': dict(
        title='HardCoRe-NAS',
        category='Efficient/Mobile',
        description=(
            'Mobile networks found by HardCoRe-NAS, a differentiable neural architecture search with hard latency '
            'constraints, built on the `MobileNetV3` class.'
        ),
    ),
    'hgnet': dict(
        title='PP-HGNet',
        category='CNN',
        description=(
            'PP-HGNet and PP-HGNetV2 (High Performance GPU Net) from PaddleClas, built from HG blocks that '
            'aggregate the outputs of a sequence of convolutions. The `ssld` weights are trained with PaddleClas '
            'SSLD distillation.'
        ),
    ),
    'hiera': dict(
        title='Hiera',
        category='ViT',
        description=(
            'Hiera is a hierarchical vision transformer without specialized modules (convolutions, shifted windows, '
            'relative position biases), relying on masked autoencoder (MAE) pretraining to learn spatial biases.'
        ),
    ),
    'hieradet-sam2': dict(
        title='HieraDet (SAM 2)',
        category='ViT',
        description=(
            'HieraDet, the Hiera based image encoder of Segment Anything 2 (SAM 2), with windowed attention and '
            'windowed position embeddings.'
        ),
    ),
    'hrnet': dict(
        title='HRNet',
        category='CNN',
        description=(
            'High-Resolution Networks keep a high resolution branch through the whole network and add lower '
            'resolution branches in parallel, repeatedly exchanging information between them.'
        ),
    ),
    'iformer': dict(
        title='iFormer',
        category='Efficient/Mobile',
        description=(
            'iFormer integrates a fast convolutional network with single-head modulation attention (SHMA) in the '
            'later stages, for mobile applications.'
        ),
    ),
    'inception-next': dict(
        title='InceptionNeXt',
        category='CNN',
        description=(
            'InceptionNeXt decomposes the large kernel depthwise convolution of ConvNeXt into parallel branches, a '
            'small square kernel, two orthogonal band kernels and an identity mapping, following Inception.'
        ),
    ),
    'inception-resnet-v2': dict(
        title='Inception-ResNet-v2',
        category='CNN',
        description=(
            'Inception-ResNet-v2 combines Inception modules with residual connections. Ported from the TensorFlow '
            'implementation and weights.'
        ),
    ),
    'inception-v3': dict(
        title='Inception-v3',
        category='CNN',
        description='Inception-v3, adapted from the torchvision `Inception3` model.',
    ),
    'inception-v4': dict(
        title='Inception-v4',
        category='CNN',
        description='Inception-v4, ported from the TensorFlow implementation and weights.',
    ),
    'lcnetv2': dict(
        title='PP-LCNetV2',
        category='Efficient/Mobile',
        description=(
            'PP-LCNetV2 from PaddleClas is a CPU oriented network built on PP-LCNet. The depthwise convolutions of '
            'the later stages are re-parameterizable multi-scale branches, and SE and shortcuts are used sparingly '
            'to avoid latency penalties on CPU.'
        ),
    ),
    'levit': dict(
        title='LeViT',
        category='Hybrid',
        description=(
            'LeViT is a hybrid network for fast inference, a convolutional stem followed by attention stages that '
            'shrink the resolution with attention based downsampling and use attention biases for position.'
        ),
    ),
    'lowformer': dict(
        title='LowFormer',
        category='Efficient/Mobile',
        description=(
            'LowFormer is a convolutional transformer backbone designed for hardware efficiency (measured throughput '
            'and latency rather than MACs). The E1 / E2 / E3 edge GPU variants are from the journal extension.'
        ),
    ),
    'mambaout': dict(
        title='MambaOut',
        category='CNN',
        description=(
            'MambaOut stacks Gated CNN blocks, Mamba blocks without the state space model (SSM) token mixer, to '
            'test whether SSMs are needed for image classification.'
        ),
    ),
    'maxxvit': dict(
        title='MaxViT and CoAtNet',
        category='Hybrid',
        description=(
            'From-scratch implementations of MaxViT (MBConv blocks with multi-axis attention, blocked local and '
            'dilated grid attention) and CoAtNet (convolution stages followed by relative attention stages), plus '
            '`timm` variants (`_rw` configs, MaxxViT).'
        ),
    ),
    'metaformer': dict(
        title='MetaFormer (PoolFormer, ConvFormer, CAFormer)',
        category='Hybrid',
        description=(
            'MetaFormer models share a general transformer block structure and vary the token mixer: pooling in '
            'PoolFormer / PoolFormerV2, separable convolutions in ConvFormer, and convolutions in the early stages '
            'with attention in the later stages in CAFormer.'
        ),
    ),
    'mlp-mixer': dict(
        title='MLP-Mixer, ResMLP and gMLP',
        category='MLP',
        description=(
            'All-MLP architectures that alternate token mixing across patches with channel mixing: MLP-Mixer, '
            'ResMLP and gMLP (gating with a spatial projection). The module docstring notes the gMLP implementation '
            'is not verified.'
        ),
    ),
    'mobilenetv3': dict(
        title='MobileNet-V3',
        category='Efficient/Mobile',
        description=(
            'MobileNet-V3 and the related networks built on the same `MobileNetV3` class: MobileNet-V4, LCNet '
            '(PP-LCNet), FBNet-V3 and TensorFlow ported MobileNet-V3 weights (`tf_*`).'
        ),
    ),
    'mobilenetv5': dict(
        title='MobileNet-V5',
        category='Encoder',
        description=(
            "The MobileNet-V5 vision encoder from Google's Gemma 3n, built from MobileNet-V4 blocks (Universal "
            'Inverted Residual, Mobile MQA) with a multi-scale fusion adapter.'
        ),
    ),
    'mobilevit': dict(
        title='MobileViT',
        category='Efficient/Mobile',
        description=(
            'MobileViT combines MobileNet-V2 inverted residual blocks with MobileViT blocks, which apply transformers '
            'to unfolded patches for global processing. MobileViT-V2 uses separable self-attention. Built on the '
            '`ByobNet` class.'
        ),
    ),
    'mvitv2': dict(
        title='MViTv2',
        category='ViT',
        description=(
            'Multiscale Vision Transformers v2, a hierarchical transformer with pooling attention, decomposed '
            'relative position embeddings and residual pooling connections.'
        ),
    ),
    'naflexvit': dict(
        title='NaFlex ViT',
        category='ViT',
        description=(
            'A Vision Transformer with the patch embedding and position encoding in one module, supporting '
            'pre-patchified inputs with variable aspect ratio and resolution (NaFlex), FlexiViT variable patch '
            'size and NaViT factorized position embeddings.'
        ),
    ),
    'nasnet': dict(
        title='NASNet',
        category='CNN',
        description=(
            "NASNet-A Large, a network of cells found by neural architecture search, from Cadene's pretrained "
            'models port.'
        ),
    ),
    'nest': dict(
        title='NesT',
        category='ViT',
        description=(
            'Nested Transformers (NesT) apply self-attention locally within non-overlapping image blocks and '
            'aggregate neighbouring blocks between stages. Weights converted from the official JAX release.'
        ),
    ),
    'nextvit': dict(
        title='Next-ViT',
        category='Hybrid',
        description=(
            'Next-ViT is a hybrid CNN / transformer for efficient deployment, stacking Next Convolution Blocks (NCB) '
            'and Next Transformer Blocks (NTB).'
        ),
    ),
    'nfnet': dict(
        title='NFNet',
        category='CNN',
        description=(
            'Normalization-Free networks, trained without batch normalization using scaled weight standardization: '
            'NFNet (with adaptive gradient clipping), NF-RegNet and pre-activation NF-ResNet models.'
        ),
    ),
    'pit': dict(
        title='PiT',
        category='ViT',
        description=(
            'Pooling-based Vision Transformers (PiT) reduce the spatial size and increase the channels of the tokens '
            'between stages with a depthwise convolution pooling layer, as in CNNs.'
        ),
    ),
    'pnasnet': dict(
        title='PNASNet',
        category='CNN',
        description=(
            "PNASNet-5 Large, found by progressive neural architecture search, from Cadene's pretrained models "
            'port.'
        ),
    ),
    'pvt-v2': dict(
        title='PVTv2',
        category='ViT',
        description=(
            'Pyramid Vision Transformer v2, a hierarchical transformer with spatial-reduction attention (linear in '
            'the `_li` variant), overlapping patch embeddings and convolutional feed-forward layers.'
        ),
    ),
    'qwen3-vit': dict(
        title='Qwen3 ViT',
        category='Encoder',
        description=(
            'The vision encoder of the Qwen3-VL / Qwen3.5 / Qwen3.8 multimodal models, a pre-norm ViT with a learned '
            'absolute position grid combined with axial 2D RoPE. Classifier variants add pooling and a linear head, '
            'the `_enc` variants keep the native projector that maps the tokens to the language model width.'
        ),
    ),
    'rdnet': dict(
        title='RDNet',
        category='CNN',
        description=(
            'RDNet (DenseNets Reloaded) revisits densely connected convolutional networks with modernized blocks and '
            'design choices.'
        ),
    ),
    'regnet': dict(
        title='RegNet',
        category='CNN',
        description=(
            'RegNetX and RegNetY networks from the regular network design spaces, RegNetZ from "Fast and Accurate '
            'Model Scaling", and `timm` additions such as the pre-activation RegNetV. Includes weights from pycls, '
            'torchvision and VISSL (SEER).'
        ),
    ),
    'repghost': dict(
        title='RepGhost',
        category='Efficient/Mobile',
        description=(
            'RepGhostNet replaces the feature concatenation of the Ghost module with re-parameterized feature '
            'reuse, folded into a single convolution path at inference.'
        ),
    ),
    'repvit': dict(
        title='RepViT',
        category='Efficient/Mobile',
        description=(
            'RepViT is a mobile CNN that brings design choices of lightweight vision transformers into MobileNet-V3 '
            'style blocks, with structural re-parameterization.'
        ),
    ),
    'res2net': dict(
        title='Res2Net',
        category='CNN',
        description=(
            'Res2Net splits the channels of the bottleneck block into groups connected hierarchically, giving '
            'several receptive field sizes within one block. Includes Res2NeXt.'
        ),
    ),
    'resnest': dict(
        title='ResNeSt',
        category='CNN',
        description=(
            'ResNeSt uses split-attention blocks, channel attention across groups of feature map splits, in a ResNet '
            'style network.'
        ),
    ),
    'resnet': dict(
        title='ResNet',
        category='CNN',
        example='resnet50.a1_in1k',
        description=(
            'Residual networks (ResNet) and the variants built on the same `ResNet` class: ResNeXt grouped '
            'convolutions, Squeeze-and-Excitation (SE) and ECA channel attention, deep / tiered stems and average '
            'pool downsampling (the "c", "d", "s" and "t" variants), anti-aliased downsampling, Wide ResNet and '
            'ResNet-RS configurations.'
        ),
    ),
    'resnetv2': dict(
        title='ResNetV2 (BiT)',
        category='CNN',
        description=(
            'Pre-activation ResNet (v2) with Group Normalization and Weight Standardization as used by Big Transfer '
            '(BiT), with the original BiT weights. Also supports the non pre-activation variant used as the hybrid '
            'Vision Transformer backbone.'
        ),
    ),
    'rexnet': dict(
        title='ReXNet',
        category='Efficient/Mobile',
        description=(
            'ReXNet revises the channel configuration of inverted residual networks to reduce representational '
            'bottlenecks. The `rexnetr_*` variants round the channels to multiples of 8.'
        ),
    ),
    'selecsls': dict(
        title='SelecSLS',
        category='CNN',
        description=(
            'SelecSLS uses selective long and short range skip connections, proposed as the core network of XNect, '
            'a real-time multi-person 3D pose estimation system.'
        ),
    ),
    'senet': dict(
        title='SENet (legacy)',
        category='CNN',
        description=(
            "SENet, SE-ResNet and SE-ResNeXt from Cadene's pretrained models (`legacy_*`). The module is deprecated "
            'in favour of the SE variants of the `ResNet` class.'
        ),
    ),
    'sequencer': dict(
        title='Sequencer',
        category='MLP',
        description=(
            'Sequencer replaces self-attention with BiLSTM layers that mix tokens along the vertical and horizontal '
            'axes, followed by channel MLPs.'
        ),
    ),
    'shvit': dict(
        title='SHViT',
        category='Efficient/Mobile',
        description=(
            'SHViT (Single-Head Vision Transformer) uses a memory efficient macro design and single-head attention '
            'applied to part of the channels.'
        ),
    ),
    'sknet': dict(
        title='SKNet',
        category='CNN',
        description=(
            'Selective Kernel Networks on a ResNet base, where SK units fuse branches with different kernel sizes '
            'using attention over the branches.'
        ),
    ),
    'starnet': dict(
        title='StarNet',
        category='Efficient/Mobile',
        description=(
            'StarNet is a deliberately simple proof-of-concept network built around the star operation, the '
            'element-wise multiplication of two branches.'
        ),
    ),
    'swiftformer': dict(
        title='SwiftFormer',
        category='Efficient/Mobile',
        description=(
            'SwiftFormer replaces the quadratic matrix multiplications of self-attention with efficient additive '
            'attention, for real-time mobile vision applications.'
        ),
    ),
    'swin-transformer': dict(
        title='Swin Transformer',
        category='ViT',
        description=(
            'Swin Transformer is a hierarchical vision transformer that computes self-attention within local '
            'windows, shifted between consecutive blocks for cross-window connections. Includes the S3 '
            '(AutoFormerV2) weights.'
        ),
    ),
    'swin-transformer-v2': dict(
        title='Swin Transformer V2',
        category='ViT',
        description=(
            'Swin Transformer V2 scales up Swin with residual post-norm, scaled cosine attention and a log-spaced '
            'continuous relative position bias that transfers across window sizes.'
        ),
    ),
    'swin-transformer-v2-cr': dict(
        title='Swin Transformer V2 (CR)',
        category='ViT',
        description=(
            "An alternative Swin Transformer V2 implementation adapted from Christoph Reich's code, designed for "
            'changing the image size together with the window size, including non-square sizes. The module '
            'docstring marks it as experimental.'
        ),
    ),
    'tiny-vit': dict(
        title='TinyViT',
        category='Hybrid',
        description=(
            'TinyViT is a family of small hierarchical vision transformers (a convolutional first stage, then local '
            'window attention), pretrained by fast distillation from large teacher models.'
        ),
    ),
    'tnt': dict(
        title='TNT',
        category='ViT',
        description=(
            'Transformer in Transformer (TNT) models the structure inside each patch with an inner transformer over '
            'sub-patches, alongside the outer transformer over patches.'
        ),
    ),
    'tresnet': dict(
        title='TResNet',
        category='CNN',
        description=(
            'TResNet is a ResNet based design for high GPU throughput, with a space-to-depth stem, anti-aliased '
            'downsampling and SE layers.'
        ),
    ),
    'twins': dict(
        title='Twins',
        category='ViT',
        description=(
            'Twins-PCPVT (Pyramid Vision Transformer with conditional position encodings) and Twins-SVT (spatially '
            'separable self-attention, locally grouped attention alternating with global sub-sampled attention).'
        ),
    ),
    'vgg': dict(
        title='VGG',
        category='CNN',
        description=(
            'VGG networks of stacked 3x3 convolutions, adapted from torchvision with `timm` functionality added.'
        ),
    ),
    'visformer': dict(
        title='Visformer',
        category='Hybrid',
        description=(
            'Visformer (Vision-friendly Transformer) transitions a transformer towards a convolutional design, with '
            'convolutional blocks in the early stage and self-attention in the later stages.'
        ),
    ),
    'vision-transformer': dict(
        title='Vision Transformer (ViT)',
        category='ViT',
        example='vit_base_patch16_224.augreg2_in21k_ft_in1k',
        description=(
            'The Vision Transformer (ViT) splits an image into fixed size patches, linearly embeds them and '
            'processes the resulting token sequence with a standard Transformer encoder. This module holds the '
            '`VisionTransformer` class and the weights for the original ViT, the "How to train your ViT?" '
            '(AugReg) and FlexiViT models, and many image-text (CLIP, SigLIP) and self-supervised '
            'pretrained image towers that share the architecture.'
        ),
    ),
    'vision-transformer-hybrid': dict(
        title='Hybrid Vision Transformer',
        category='Hybrid',
        description=(
            'Vision Transformers whose patch tokens come from a convolutional backbone (ResNet / ResNetV2 stem or '
            'stages) instead of a linear patch embedding, using the `VisionTransformer` class.'
        ),
    ),
    'vision-transformer-relpos': dict(
        title='Vision Transformer (relative position)',
        category='ViT',
        description=(
            'Vision Transformers using relative position biases instead of absolute position embeddings. The module '
            'docstring marks these models as experimental.'
        ),
    ),
    'vision-transformer-sam': dict(
        title='Segment Anything ViT',
        category='ViT',
        description=(
            'The ViT image encoder of the Segment Anything Model (SAM), a plain ViT backbone with windowed and '
            'global attention blocks and relative position embeddings as in ViTDet.'
        ),
    ),
    'vitamin': dict(
        title='ViTamin',
        category='Hybrid',
        description=(
            'ViTamin is a vision model designed for vision-language models, with convolutional (MBConv) stages '
            'followed by transformer stages. The weights are CLIP image towers.'
        ),
    ),
    'volo': dict(
        title='VOLO',
        category='ViT',
        description=(
            'Vision Outlooker (VOLO) adds outlook attention, which encodes fine-level features from local '
            'neighbourhoods, before transformer stages that operate on coarser tokens.'
        ),
    ),
    'vovnet': dict(
        title='VoVNet',
        category='CNN',
        description=(
            'VoVNet uses One-Shot Aggregation (OSA) modules, which concatenate the outputs of all layers of a block '
            'once at its end. VoVNetV2 (from CenterMask) adds residual connections and effective SE (eSE) attention.'
        ),
    ),
    'xception': dict(
        title='Xception (legacy)',
        category='CNN',
        description=(
            'The original Xception, depthwise separable convolutions with residual connections, with weights ported '
            'from Keras (`legacy_xception`).'
        ),
    ),
    'xception-aligned': dict(
        title='Aligned Xception',
        category='CNN',
        description=(
            'Aligned Xception (41, 65, 71 layers) as modified in DeepLab, implemented from scratch and compatible '
            'with the TensorFlow DeepLab weights.'
        ),
    ),
    'xcit': dict(
        title='XCiT',
        category='ViT',
        description=(
            'Cross-Covariance Image Transformers (XCiT) replace token self-attention with cross-covariance attention '
            'across feature channels, linear in the number of tokens, and add local patch interaction layers.'
        ),
    ),
}

# A paper reference in a module docstring is one line: ``* `Title` - https://...`` (bullet ``*`` or ``-``, any indent).
_PAPER_LINE_RE = re.compile(r'^\s*[*-]\s+`(?P<title>[^`]+)`\s*[-\u2013]\s*(?P<url>https?://[^\s<>`]+)')
_ARXIV_ID_RE = re.compile(r'(\d{4}\.\d{4,5})(v\d+)?')
_BIBTEX_START_RE = re.compile(r'^\s*@\w+\s*\{')


# --------------------------------------------------------------------------------------------------------------------
# Paper references from module docstrings


@dataclass
class Paper:
    """A paper reference parsed from a module docstring or a pretrained config."""
    url: str
    title: Optional[str] = None
    key: str = ''


def _paper_key(url: str) -> str:
    """Normalized key used to de-duplicate paper links (arXiv id without version, else the url)."""
    if 'arxiv.org' in url:
        m = _ARXIV_ID_RE.search(url)
        if m:
            return f'arxiv:{m.group(1)}'
    return url.rstrip('/').lower()


def _normalize_paper_url(url: str) -> str:
    """Point arXiv pdf links to the abstract page."""
    url = url.rstrip('.,;)')
    if 'arxiv.org' in url:
        m = _ARXIV_ID_RE.search(url)
        if m:
            return f'https://arxiv.org/abs/{m.group(1)}{m.group(2) or ""}'
    return url


def _split_bibtex(doc: str) -> Tuple[List[str], List[str]]:
    """Split a docstring into BibTeX entries and the remaining lines."""
    entries = []
    other = []
    lines = doc.splitlines()
    i = 0
    while i < len(lines):
        if _BIBTEX_START_RE.match(lines[i]):
            depth = 0
            block = []
            while i < len(lines):
                block.append(lines[i])
                depth += lines[i].count('{') - lines[i].count('}')
                i += 1
                if depth <= 0:
                    break
            indent = min(len(ln) - len(ln.lstrip()) for ln in block if ln.strip())
            entries.append('\n'.join(ln[indent:] for ln in block).strip())
        else:
            other.append(lines[i])
            i += 1
    return entries, other


def parse_papers(doc: Optional[str]) -> Tuple[List[Paper], List[str]]:
    """Parse paper references and BibTeX entries from a module docstring.

    Paper references follow the ``timm/models`` docstring convention of one line per paper,
    ``* `Title` - https://...`` (bullet ``*`` or ``-``, any indent, title in backticks). Other lines, including other
    links (code, weights), are ignored. BibTeX entries are returned as is for the citation block.

    Args:
        doc: Module docstring.

    Returns:
        Paper references in docstring order (de-duplicated) and the raw BibTeX entries.
    """
    if not doc:
        return [], []
    bibtex, lines = _split_bibtex(doc)
    papers: Dict[str, Paper] = {}
    for line in lines:
        m = _PAPER_LINE_RE.match(line)
        if not m:
            continue
        url = _normalize_paper_url(m.group('url'))
        key = _paper_key(url)
        if key not in papers:
            papers[key] = Paper(url=url, title=' '.join(m.group('title').split()), key=key)
    return list(papers.values()), bibtex


def _cfg_arxiv_urls(cfg: Any) -> List[str]:
    """arXiv abstract urls of the ``paper_ids`` field of a pretrained config."""
    urls = []
    for pid in str(cfg.paper_ids or '').split(','):
        m = _ARXIV_ID_RE.search(pid)
        if m and 'arxiv' in pid.lower():
            urls.append(f'https://arxiv.org/abs/{m.group(1)}')
    return urls


def config_papers(pretrained_cfgs: Sequence[Any]) -> List[Paper]:
    """Paper references from the ``paper_ids`` / ``paper_name`` fields of pretrained configs."""
    papers: Dict[str, Paper] = {}
    for cfg in pretrained_cfgs:
        for url in _cfg_arxiv_urls(cfg):
            key = _paper_key(url)
            if key not in papers:
                papers[key] = Paper(url=url, title=cfg.paper_name, key=key)
            elif cfg.paper_name and not papers[key].title:
                papers[key].title = cfg.paper_name
    return list(papers.values())


# --------------------------------------------------------------------------------------------------------------------
# Pretrained weight sources

# First tokens of a pretrained tag that describe the data or training schedule rather than the source of a weight,
# e.g. ``in1k``, ``in22k_ft_in1k``, ``300ep_in1k``, ``r160_in1k``, ``e300_in1k``, ``patch16_in21k``, ``pt``.
_TAG_NO_SOURCE_RE = re.compile(r'^(in\d+k|inw\d+k|\d\w*|[er]\d+|patch\d+|ft|pt|dist\w*)$')
_OTHER_SOURCE = 'other'


@dataclass
class WeightGroup:
    """Pretrained weights of a family that share a source."""
    key: str
    label: str
    note: str = ''
    weights: List[str] = field(default_factory=list)


def _short_title(title: str) -> str:
    """Short label for a paper title, the part before a colon if there is one (e.g. ``ConvNeXt-V2: ...``)."""
    head = title.split(':')[0].strip()
    return head if head != title and len(head) >= 3 else title


def _url_label(url: str) -> str:
    """Short label for an origin url, ``owner/repo`` for GitHub / Hugging Face Hub urls, else the host."""
    parts = url.split('://', 1)[-1].rstrip('/').split('/')
    host = parts[0].lower()
    host = host[4:] if host.startswith('www.') else host
    if host in ('github.com', 'huggingface.co') and len(parts) >= 3:
        return '/'.join(parts[1:3])
    return host


def weight_source(weight: str, paper_titles: Dict[str, str]) -> WeightGroup:
    """Source of a pretrained weight, for grouping the weights of a family page.

    The pretrained config ``paper_ids`` take precedence, then ``origin_url``, then a Hub organization other than
    ``timm``, then the first token of the pretrained tag unless it only names the data or schedule (``in1k``,
    ``300ep``, ...). Weights without any of these are grouped as other.

    Args:
        weight: Pretrained weight name, ``arch.tag``.
        paper_titles: Paper titles keyed by paper key, from the module docstring and pretrained configs.

    Returns:
        An empty group for the source, with its key, label and note.
    """
    cfg = get_pretrained_cfg(weight)
    urls = _cfg_arxiv_urls(cfg)
    if urls:
        key = _paper_key(urls[0])
        title = paper_titles.get(key) or cfg.paper_name
        label = _short_title(title) if title else key.replace('arxiv:', 'arXiv:')
        return WeightGroup(f'paper:{key}', label, f'Pretrained configs reference [{_md(title or label)}]({urls[0]}).')
    if cfg.origin_url:
        url = cfg.origin_url
        return WeightGroup(f'origin:{url}', _url_label(url), f'Origin: [{_md(url.split("://", 1)[-1])}]({url})')
    org = (cfg.hf_hub_id or '').split('/')[0]
    if org and org != 'timm':
        return WeightGroup(f'hub:{org}', org, f'Hosted by [`{org}`]({_HUB_URL}/{org}) on the Hugging Face Hub.')
    token = weight.split('.', 1)[1].split('_')[0] if '.' in weight else ''
    if token and not _TAG_NO_SOURCE_RE.match(token):
        return WeightGroup(f'tag:{token}', f'`{token}` tags')
    return WeightGroup(_OTHER_SOURCE, 'Other')


def group_weights(weights: Sequence[str], paper_titles: Dict[str, str]) -> List[WeightGroup]:
    """Group pretrained weights by source (see ``weight_source``).

    Sources with a single weight are folded into the other group. If fewer than two sources remain the weights are
    returned as one unlabeled group. Groups are ordered by size, the other group last.
    """
    groups: Dict[str, WeightGroup] = {}
    for w in weights:
        source = weight_source(w, paper_titles)
        groups.setdefault(source.key, source).weights.append(w)
    other = groups.pop(_OTHER_SOURCE, WeightGroup(_OTHER_SOURCE, 'Other'))
    for key in [k for k, g in groups.items() if len(g.weights) < 2]:
        other.weights += groups.pop(key).weights
    if len(groups) < 2:
        return [WeightGroup('', '', weights=list(weights))] if weights else []
    order = {w: i for i, w in enumerate(weights)}
    other.weights.sort(key=order.get)
    ordered = sorted(groups.values(), key=lambda g: (-len(g.weights), g.label.lower()))
    return ordered + ([other] if other.weights else [])


# --------------------------------------------------------------------------------------------------------------------
# Results / benchmark data


def load_results(path: Path) -> Dict[str, List[Dict[str, str]]]:
    """Load an ImageNet results csv, keyed by full ``arch.tag`` name (one row per evaluated image size)."""
    rows = defaultdict(list)
    if not path.exists():
        return rows
    with open(path, newline='') as f:
        for row in csv.DictReader(f):
            rows[row['model']].append(row)
    return rows


def load_benchmark(
        results_dir: Path,
        architectures: Sequence[str],
        path: Optional[Path] = None,
) -> Tuple[Optional[Path], Dict[Tuple[str, int], Dict[str, str]]]:
    """Load an inference benchmark csv, keyed by ``(arch, img_size)``.

    Params and GMACs do not depend on the benchmark hardware, so when no path is given the csv covering the most
    currently registered architectures is used (the newest benchmark runs cover the most models).
    """
    archs = set(architectures)
    best = None
    if path is None:
        for p in sorted(results_dir.glob('benchmark-infer-*.csv')):
            with open(p, newline='') as f:
                rows = list(csv.DictReader(f))
            if 'infer_gmacs' not in rows[0] or 'param_count' not in rows[0]:
                continue
            coverage = len({r['model'] for r in rows} & archs)
            if best is None or coverage > best[0]:
                best = (coverage, p, rows)
        if best is None:
            return None, {}
        path, rows = best[1], best[2]
    else:
        with open(path, newline='') as f:
            rows = list(csv.DictReader(f))
    return path, {(r['model'], int(r['infer_img_size'])): r for r in rows}


# --------------------------------------------------------------------------------------------------------------------
# Model API capability probe

# (key, label, Model API page anchor), in display order. Anchors are the section slugs of the Model API page.
FEATURES = (
    ('features_only', '`features_only=True` feature maps', 'intermediate-features'),
    ('forward_intermediates', '`forward_intermediates()`', 'intermediate-features'),
    ('prune_intermediate_layers', '`prune_intermediate_layers()`', 'intermediate-features'),
    ('flexible_input', 'Any input size, no changes needed', 'input-size'),
    ('set_input_size', '`set_input_size()`', 'input-size'),
    ('dynamic_img_size', '`dynamic_img_size=True`', 'input-size'),
    ('grad_checkpointing', '`set_grad_checkpointing()`', 'training-hooks'),
    ('group_matcher', 'Layer-wise LR decay (`group_matcher()`)', 'training-hooks'),
    ('reset_classifier', '`reset_classifier()`', 'classifier'),
)
_MATRIX_HEADERS = {
    'features_only': '`features_only`',
    'forward_intermediates': '`forward_intermediates`',
    'prune_intermediate_layers': '`prune_intermediate_layers`',
    'flexible_input': 'Any input size',
    'set_input_size': '`set_input_size`',
    'dynamic_img_size': '`dynamic_img_size`',
    'grad_checkpointing': 'Grad checkpointing',
    'group_matcher': 'Layer decay',
    'reset_classifier': '`reset_classifier`',
}

# Probe outcomes. SQUARE: works for square sizes other than the default but not for a non-square size.
YES, NO, SQUARE, NOT_NEEDED = 'yes', 'no', 'square', 'n/a'
_SYMBOLS = {YES: '✓', NO: '✗', SQUARE: '✓ (square)', NOT_NEEDED: '–'}
_LEGEND = (
    '✓ supported, ✓ (square) works for square sizes only, ✗ not supported, – not needed (the model already accepts '
    'any input size).'
)


@dataclass
class ProbeResult:
    """Model API probe outcome for one model class (probed on one representative architecture)."""
    model_class: str
    arch: str
    img_size: Tuple[int, int]
    status: Dict[str, str] = field(default_factory=dict)
    errors: Dict[str, str] = field(default_factory=dict)
    feature_reductions: List[int] = field(default_factory=list)
    seconds: float = 0.


def _first_tensor(out: Any) -> torch.Tensor:
    if isinstance(out, (tuple, list)):
        out = out[0]
    if isinstance(out, dict):
        out = next(iter(out.values()))
    if not isinstance(out, torch.Tensor):
        raise TypeError(f'unexpected output type {type(out).__name__}')
    return out


def _forward_ok(model: torch.nn.Module, size: Tuple[int, int], batch_size: int = 1) -> None:
    """Run a forward pass, raise if it fails or a classifier output is not ``(batch_size, num_classes)``."""
    out = _first_tensor(model(torch.randn(batch_size, 3, *size)))
    num_classes = getattr(model, 'num_classes', 0)
    if hasattr(model, 'reset_classifier') and num_classes:
        if tuple(out.shape) != (batch_size, num_classes):
            raise ValueError(f'output shape {tuple(out.shape)}, expected {(batch_size, num_classes)}')
    elif out.shape[0] != batch_size:
        raise ValueError(f'output shape {tuple(out.shape)}')


def _size_support(model: torch.nn.Module, square: Tuple[int, int], rect: Tuple[int, int]) -> str:
    """Forward at a non-default square size, then a non-square size. Raise if the square size fails."""
    _forward_ok(model, square)
    try:
        _forward_ok(model, rect)
    except Exception:
        return SQUARE
    return YES


def _err(e: BaseException) -> str:
    return f'{type(e).__name__}: {str(e).splitlines()[0][:200] if str(e) else ""}'


def probe_model_api(arch: str, model_class: str, max_size: int = 384) -> ProbeResult:
    """Functionally probe the model API of a randomly initialized model on CPU.

    Signature or ``hasattr`` checks alone are unreliable (some classes accept and silently drop unknown kwargs, some
    methods exist but assert), so each feature counts only if a small call using it actually works. Probe steps catch
    any exception on purpose, a model failing a feature for any reason means the feature is not usable.

    Models with a default input size above ``max_size`` (large VLM encoders, SAM backbones) are probed at about
    256 px if they accept it, the features don't depend on the size and the probe is much faster.

    Args:
        arch: Architecture name, ideally the smallest of its class.
        model_class: Name of the model class, for reporting.
        max_size: Default input sizes above this are reduced if the model accepts it.

    Returns:
        The probe result.
    """
    t0 = time.perf_counter()
    cfg = get_pretrained_cfg(arch)
    h, w = cfg.input_size[-2:]
    torch.manual_seed(0)
    base = timm.create_model(arch, pretrained=False).eval()

    # A size step that is a multiple of the network stride (or patch size), at least 32 px.
    stride = 32
    feature_info = getattr(base, 'feature_info', None)
    if isinstance(feature_info, (list, tuple)) and feature_info and feature_info[-1].get('reduction'):
        stride = int(feature_info[-1]['reduction'])
    step = stride * math.ceil(32 / stride)

    with torch.no_grad():
        reduced = None
        if max(h, w) > max_size:
            size = stride * max(1, round(256 / stride))
            try:
                _forward_ok(base, (size, size))
                reduced = (size, size)
            except Exception:
                pass
        if reduced is not None:
            h, w = reduced
        else:
            _forward_ok(base, (h, w))  # must work, anything below is meaningless otherwise
    res = ProbeResult(model_class=model_class, arch=arch, img_size=(h, w))
    status, errors = res.status, res.errors
    square, rect = (h + step, w + step), (h + step, w + 2 * step)

    def _check(key: str, fn) -> None:
        try:
            with torch.no_grad():
                status[key] = fn()
        except Exception as e:
            status[key] = NO
            errors[key] = _err(e)

    _check('flexible_input', lambda: _size_support(base, square, rect))
    flexible = status['flexible_input'] != NO

    def _features_only():
        model = timm.create_model(arch, pretrained=False, features_only=True).eval()
        feats = model(torch.randn(1, 3, h, w))
        reductions = [int(r) for r in model.feature_info.reduction()]  # for the selected out_indices
        if not isinstance(feats, (list, tuple)) or not feats or len(feats) != len(reductions):
            raise ValueError('unexpected feature output')
        res.feature_reductions = reductions
        return YES
    _check('features_only', _features_only)

    def _forward_intermediates():
        feats = base.forward_intermediates(torch.randn(1, 3, h, w), intermediates_only=True)
        if not isinstance(feats, (list, tuple)) or not feats or not all(isinstance(f, torch.Tensor) for f in feats):
            raise ValueError('unexpected intermediates output')
        return YES
    _check('forward_intermediates', _forward_intermediates)

    def _prune():
        model = copy.deepcopy(base)
        num_params = sum(p.numel() for p in model.parameters())
        model.prune_intermediate_layers(indices=[0], prune_norm=True, prune_head=True)
        feats = model.forward_intermediates(torch.randn(1, 3, h, w), indices=[0], intermediates_only=True)
        if len(feats) != 1:
            raise ValueError(f'{len(feats)} intermediates after pruning to one')
        if sum(p.numel() for p in model.parameters()) >= num_params:
            raise ValueError('no parameters removed')
        return YES
    _check('prune_intermediate_layers', _prune)

    def _set_input_size():
        if not hasattr(base, 'set_input_size'):
            if flexible:
                return NOT_NEEDED
            raise AttributeError('no set_input_size()')
        try:
            model = copy.deepcopy(base)
            model.set_input_size(img_size=rect)
            _forward_ok(model, rect)
            return YES
        except Exception:
            model = copy.deepcopy(base)
            model.set_input_size(img_size=square)
            _forward_ok(model, square)
            return SQUARE
    _check('set_input_size', _set_input_size)

    def _dynamic_img_size():
        try:
            model = timm.create_model(arch, pretrained=False, dynamic_img_size=True).eval()
            enabled = any(getattr(m, 'dynamic_img_size', None) is True for m in model.modules())
            if not enabled:
                raise ValueError('dynamic_img_size=True accepted but not enabled')
        except Exception:
            if flexible:
                return NOT_NEEDED
            raise
        return _size_support(model, square, rect)
    _check('dynamic_img_size', _dynamic_img_size)

    def _group_matcher():
        layer_map = group_parameters(base, base.group_matcher(coarse=False), reverse=True)
        if len(set(layer_map.values())) < 2:
            raise ValueError('all parameters in one group')
        return YES
    _check('group_matcher', _group_matcher)

    def _grad_checkpointing():
        # Checkpointed segments are re-run during backward, count module forward calls to see that it happens.
        model = copy.deepcopy(base).train()
        model.set_grad_checkpointing(True)
        calls = [0]

        def _hook(*args):
            calls[0] += 1

        handles = [m.register_forward_hook(_hook) for m in model.modules()]
        try:
            with torch.enable_grad():
                out = model(torch.randn(2, 3, h, w))
                outs = out if isinstance(out, (tuple, list)) else (out,)
                loss = sum(o.float().mean() for o in outs if isinstance(o, torch.Tensor))
                forward_calls = calls[0]
                loss.backward()
        finally:
            for handle in handles:
                handle.remove()
        if calls[0] == forward_calls:
            raise ValueError('set_grad_checkpointing(True) accepted but nothing is recomputed in backward')
        return YES
    _check('grad_checkpointing', _grad_checkpointing)

    def _reset_classifier():
        model = copy.deepcopy(base)
        model.reset_classifier(7)
        _forward_ok(model, (h, w))
        if model.num_classes != 7:
            raise ValueError('num_classes not updated')
        model.reset_classifier(0)
        out = _first_tensor(model(torch.randn(1, 3, h, w)))
        if out.ndim != 2:
            raise ValueError(f'reset_classifier(0) output shape {tuple(out.shape)}')
        return YES
    _check('reset_classifier', _reset_classifier)

    res.seconds = time.perf_counter() - t0
    return res


# --------------------------------------------------------------------------------------------------------------------
# Family data


@dataclass
class ArchInfo:
    """Registered architecture of a family."""
    name: str
    model_class: str
    params_m: Optional[float]
    gmacs: Optional[str]
    input_size: Tuple[int, int]
    num_pretrained: int


@dataclass
class FamilyData:
    """Everything needed to render a family page."""
    slug: str
    spec: Dict[str, Any]
    archs: List[ArchInfo]
    weights: List[str]
    papers: List[Paper]
    weight_papers: List[Paper]
    bibtex: List[str]
    weight_groups: List[WeightGroup]
    probes: Dict[str, ProbeResult]
    example: Optional[str]
    issues: List[str]


def _fmt_size(size: Sequence[int]) -> str:
    h, w = size[-2:]
    return str(h) if h == w else f'{h}x{w}'


def _params_match(benchmark_params: float, params: Optional[float]) -> bool:
    """Whether a benchmark param count (in M, rounded) matches a model's param count."""
    return params is not None and abs(benchmark_params - params) <= max(0.01, 0.005 * params)


def _reparameterized_params(name: str) -> Optional[float]:
    """Param count (in M) of a model in its fused (reparameterized) deployment form, None if unavailable.

    Built on CPU, reparameterization does not work for all models on the meta device.
    """
    from timm.utils.model import reparameterize_model
    try:
        with warnings.catch_warnings(), torch.no_grad():
            warnings.simplefilter('ignore')
            model = reparameterize_model(timm.create_model(name, pretrained=False).eval())
    except Exception:
        return None
    return sum(p.numel() for p in model.parameters()) / 1e6


def collect_family(
        slug: str,
        spec: Dict[str, Any],
        results: Dict[str, List[Dict[str, str]]],
        benchmark: Dict[Tuple[str, int], Dict[str, str]],
        probe: bool = True,
        log=print,
) -> FamilyData:
    """Gather the registry, results, docstring and probe data for one family."""
    issues = []
    spec = dict(spec, modules=tuple(spec.get('modules') or (slug.replace('-', '_'),)))
    if spec['category'] not in CATEGORIES:
        raise ValueError(f'family {slug}: unknown category {spec["category"]}')
    filters = dict(
        filter=spec.get('include', ''),
        module=list(spec['modules']),
        exclude_filters=spec.get('exclude', ''),
    )
    arch_names = timm.list_models(**filters)
    arch_order = {name: i for i, name in enumerate(arch_names)}
    weights = sorted(timm.list_models(pretrained=True, **filters), key=lambda w: (arch_order[w.split('.')[0]], w))
    if not arch_names:
        raise ValueError(f'family {slug}: no architectures registered for {spec["modules"]}')

    num_pretrained = defaultdict(int)
    for w in weights:
        num_pretrained[w.split('.')[0]] += 1

    archs = []
    by_class = defaultdict(list)
    for name in arch_names:
        # Construction on the meta device is cheap, gives the model class and a param count fallback.
        with warnings.catch_warnings(), torch.device('meta'):
            warnings.simplefilter('ignore')
            model = timm.create_model(name, pretrained=False)
        model_class = type(model).__name__
        meta_params = sum(p.numel() for p in model.parameters()) / 1e6
        del model
        by_class[model_class].append((meta_params, name))

        input_size = tuple(get_pretrained_cfg(name).input_size[-2:])
        bench = benchmark.get((name, input_size[-1])) if input_size[0] == input_size[1] else None
        if bench and not _params_match(float(bench['param_count']), meta_params):
            if _params_match(float(bench['param_count']), _reparameterized_params(name)):
                pass  # benchmarked in the fused (reparameterized) deployment form, the row is current
            else:
                # the benchmark predates a change to the architecture, its params / GMACs no longer apply
                issues.append(
                    f'{name}: benchmark param_count {bench["param_count"]}M, current code {meta_params:.2f}M, '
                    f'stale benchmark row not used')
                bench = None
        elif not bench:
            issues.append(f'{name}: no benchmark row at img_size {_fmt_size(input_size)}')
        params_m = float(bench['param_count']) if bench else round(meta_params, 2)
        archs.append(ArchInfo(
            name=name,
            model_class=model_class,
            params_m=params_m,
            gmacs=f'{float(bench["infer_gmacs"]):.2f}' if bench else None,
            input_size=input_size,
            num_pretrained=num_pretrained[name],
        ))

    papers, bibtex = [], []
    for module in spec['modules']:
        source = (_REPO_ROOT / 'timm' / 'models' / f'{module}.py').read_text()
        p, b = parse_papers(ast.get_docstring(ast.parse(source)))
        papers += p
        bibtex += b
    seen = {p.key for p in papers}
    weight_papers = [p for p in config_papers([get_pretrained_cfg(w) for w in weights]) if p.key not in seen]
    if not papers:
        issues.append(f'no paper references parsed from the docstring of {", ".join(spec["modules"])}')
    paper_titles = {p.key: p.title for p in papers + weight_papers if p.title}
    weight_groups = group_weights(weights, paper_titles)

    for w in weights:
        if not get_pretrained_cfg(w).hf_hub_id:
            issues.append(f'{w}: no hf_hub_id')

    probes = {}
    if probe:
        for model_class, entries in sorted(by_class.items()):
            # Smallest architecture of the class in this family. test_* models are listed like any other, but not
            # used for the probe as they use deliberately unusual configs (e.g. test_vit enables dynamic_img_size),
            # unless the class has nothing else.
            arch = min([e for e in entries if not e[1].startswith('test_')] or entries)[1]
            try:
                probes[model_class] = probe_model_api(arch, model_class)
            except Exception as e:
                issues.append(f'probe of {model_class} ({arch}) failed: {_err(e)}')
                continue
            r = probes[model_class]
            log(f'  probed {model_class} with {arch} in {r.seconds:.1f}s')
            for key, err in r.errors.items():
                log(f'    {key}: {err}')

    example = spec.get('example')
    if example and example not in weights:
        issues.append(f'example weight {example} is not a pretrained tag of this family')
        example = None
    if not example:
        example = _pick_example(archs, weights, results)

    return FamilyData(
        slug=slug,
        spec=spec,
        archs=archs,
        weights=weights,
        papers=papers,
        weight_papers=weight_papers,
        bibtex=bibtex,
        weight_groups=weight_groups,
        probes=probes,
        example=example,
        issues=issues,
    )


def _pick_example(archs: Sequence[ArchInfo], weights: Sequence[str], results: Dict[str, List]) -> Optional[str]:
    """Default usage example: the ImageNet-1k weight closest to 25M params (a typical base size), not a test model."""
    candidates = []
    params = {a.name: a.params_m for a in archs}
    for w in weights:
        arch = w.split('.')[0]
        if arch.startswith('test_') or w not in results or params.get(arch) is None:
            continue
        candidates.append((abs(math.log(params[arch] / 25.)), w))
    return min(candidates)[1] if candidates else (weights[0] if weights else None)


def _top1(name: str, results: Dict[str, List[Dict[str, str]]]) -> Optional[Dict[str, str]]:
    """Results row for a weight at its pretrained config test size (else input size), else its best row."""
    rows = results.get(name)
    if not rows:
        return None
    cfg = get_pretrained_cfg(name)
    eval_size = (cfg.test_input_size or cfg.input_size)[-1]
    for row in rows:
        if int(row['img_size']) == eval_size:
            return row
    return max(rows, key=lambda r: float(r['top1']))


# --------------------------------------------------------------------------------------------------------------------
# Rendering


def _md(text: str) -> str:
    """Escape text for a markdown table cell / MDX prose."""
    return text.replace('|', '\\|').replace('<', '&lt;').replace('{', '&#123;').replace('}', '&#125;')


def _table(headers: Sequence[str], rows: Sequence[Sequence[str]], align: Optional[Sequence[str]] = None) -> str:
    align = align or ['l'] * len(headers)
    sep = ['---:' if a == 'r' else '---' for a in align]
    lines = ['| ' + ' | '.join(headers) + ' |', '|' + '|'.join(sep) + '|']
    lines += ['| ' + ' | '.join(r) + ' |' for r in rows]
    return '\n'.join(lines)


def _feature_cell(r: ProbeResult, key: str) -> str:
    value = r.status.get(key, NO)
    cell = _SYMBOLS[value]
    if key == 'features_only' and value == YES and r.feature_reductions:
        cell += ' (strides ' + ', '.join(str(x) for x in r.feature_reductions) + ')'
    return cell


def _weight_table(weights: Sequence[str], results: Dict[str, List[Dict[str, str]]]) -> str:
    rows = []
    for w in weights:
        cfg = get_pretrained_cfg(w)
        row = _top1(w, results)
        if cfg.hf_hub_id:
            hub_text = 'timm' if cfg.hf_hub_id == f'timm/{w}' else cfg.hf_hub_id
            hub = f'[{_md(hub_text)}]({_HUB_URL}/{cfg.hf_hub_id})'
        elif cfg.url:
            hub = f'[original]({cfg.url})'
        else:
            hub = '-'
        input_size = _fmt_size(cfg.input_size)
        if cfg.test_input_size and tuple(cfg.test_input_size) != tuple(cfg.input_size):
            input_size += f' (test {_fmt_size(cfg.test_input_size)})'
        rows.append([
            f'`{w}`',
            input_size,
            row['top1'] if row else '-',
            row['img_size'] if row else '-',
            str(cfg.num_classes) if cfg.num_classes else 'none',
            _md(cfg.license or '-'),
            hub,
        ])
    return _table(
        ['Weight', 'Input size', 'Top-1 (%)', 'Eval size', 'Classes', 'License', 'Hub'],
        rows,
        ['l', 'r', 'r', 'r', 'r', 'l', 'l'],
    )


def render_family(data: FamilyData, results: Dict[str, List[Dict[str, str]]]) -> str:
    """Render the MDX page of a family."""
    spec = data.spec
    modules = spec['modules']
    module_links = ', '.join(f'[`timm/models/{m}.py`]({_GITHUB_BLOB}/timm/models/{m}.py)' for m in modules)
    num_in1k = sum(1 for w in data.weights if w in results)
    out = [
        _GENERATED_NOTE,
        '',
        f'# {spec["title"]}',
        '',
        f'**Category:** {spec["category"]} · **Code:** {module_links} · **Architectures:** {len(data.archs)} · '
        f'**Pretrained weights:** {len(data.weights)} ({num_in1k} with ImageNet-1k results)',
        '',
        spec['description'],
        '',
    ]

    def _paper_item(p: Paper) -> str:
        title = _md(p.title) if p.title else p.key.replace('arxiv:', 'arXiv:')
        return f'* [{title}]({p.url})' if p.url else f'* {title}'

    out += ['## Papers', '']
    if data.papers:
        out += [_paper_item(p) for p in data.papers]
    else:
        out.append('The module docstring does not reference any papers.')
    if data.weight_papers:
        out += ['', 'Referenced by pretrained weights:', '']
        out += [_paper_item(p) for p in data.weight_papers]
    out.append('')

    out += [
        '## Usage',
        '',
        'See the [Quickstart](../quickstart) for loading pretrained weights, image preprocessing and fine-tuning, '
        'and [Feature Extraction](../feature_extraction) for using the models as backbones.',
        '',
    ]
    if data.example:
        out += [
            '```py',
            '>>> import timm',
            f">>> model = timm.create_model('{data.example}', pretrained=True)",
            '>>> data_config = timm.data.resolve_model_data_config(model)',
            '```',
            '',
        ]

    out += ['## Model API support', '']
    if data.probes:
        classes = sorted(data.probes)
        headers = ['Feature'] + [f'`{c}`' for c in classes]
        rows = []
        for key, label, anchor in FEATURES:
            link = f'[{label}]({_MODEL_API_PAGE}#{anchor})'
            rows.append([link] + [_feature_cell(data.probes[c], key) for c in classes])
        out += [_table(headers, rows), '']
        probed = ', '.join(
            f'`{c}` with `{data.probes[c].arch}` at {_fmt_size(data.probes[c].img_size)}' for c in classes)
        out += [
            f'{_LEGEND} Checked by running each feature on a randomly initialized model ({probed}), other '
            f'architectures of the same class are expected to behave the same. See the '
            f'[Model API]({_MODEL_API_PAGE}) page for details.',
            '',
        ]
    else:
        out += ['Not probed.', '']

    out += ['## Architectures', '']
    multi_class = len({a.model_class for a in data.archs}) > 1
    headers = ['Architecture'] + (['Class'] if multi_class else []) + [
        'Params (M)', 'GMACs', 'Input size', 'Pretrained weights']
    align = ['l'] + (['l'] if multi_class else []) + ['r', 'r', 'r', 'r']
    rows = []
    for a in data.archs:
        rows.append([f'`{a.name}`'] + ([f'`{a.model_class}`'] if multi_class else []) + [
            f'{a.params_m:.2f}' if a.params_m is not None else '-',
            a.gmacs or '-',
            _fmt_size(a.input_size),
            str(a.num_pretrained),
        ])
    out += [
        _table(headers, rows, align),
        '',
        'GMACs and parameter counts are for the default input size and classifier of each architecture, from the '
        '[benchmark results](https://github.com/huggingface/pytorch-image-models/tree/main/results).',
        '',
    ]

    out += [
        '## Pretrained weights',
        '',
        'Top-1 is ImageNet-1k validation accuracy from [`results-imagenet.csv`]'
        '(https://github.com/huggingface/pytorch-image-models/blob/main/results/results-imagenet.csv) at the '
        'listed eval size, - if the weight has no ImageNet-1k result (e.g. pretraining or image-text weights). '
        'Classes is the size of the pretrained classifier, none for weights without one.',
        '',
    ]
    grouped = len(data.weight_groups) > 1
    if grouped:
        out += [
            'Weights are grouped by source: the paper or origin given in the pretrained config, else a Hub '
            'organization other than `timm`, else the first part of the pretrained tag (`architecture.tag`). Sources '
            'with a single weight are listed under other.',
            '',
        ]
    for group in data.weight_groups:
        if grouped:
            out += [f'### {group.label}', '']
            if group.note:
                out += [group.note, '']
        out += [_weight_table(group.weights, results), '']
    if not data.weight_groups:
        out += ['No pretrained weights.', '']

    if data.bibtex:
        out += ['## Citation', '', '```bibtex', '\n\n'.join(data.bibtex), '```', '']
    return '\n'.join(out)


def render_support_matrix(families: Sequence[FamilyData]) -> str:
    """Render the Model API support matrix, one row per family (docs page).

    A family with several model classes gets one row per distinct probe outcome, listing the classes that share it.
    """
    keys = [k for k, _, _ in FEATURES]
    headers = ['Family', 'Classes'] + [_MATRIX_HEADERS[k] for k in keys]
    rows = []
    for data in sorted(families, key=lambda d: d.spec['title'].lower()):
        family = f'[{_md(data.spec["title"])}](models/{data.slug})'
        by_status: Dict[Tuple[str, ...], List[str]] = {}
        for c in sorted(data.probes):
            status = tuple(_SYMBOLS[data.probes[c].status.get(k, NO)] for k in keys)
            by_status.setdefault(status, []).append(c)
        if not by_status:
            rows.append([family, 'not probed'] + ['?'] * len(keys))
        for i, (status, classes) in enumerate(by_status.items()):
            rows.append([family if i == 0 else '', ', '.join(f'`{c}`' for c in classes)] + list(status))
    return '\n'.join([
        _GENERATED_NOTE,
        '',
        _table(headers, rows),
        '',
        f'{_LEGEND} Each model class of a family is checked by running every feature on a randomly initialized model '
        'of its smallest (non-test) architecture in the family. Classes with the same results share a row, the '
        'family page lists the architecture used for each.',
        '',
    ])


def _plural(n: int, noun: str) -> str:
    return f'{n} {noun}' + ('' if n == 1 else 's')


def render_index(families: Sequence[FamilyData]) -> str:
    """Render the model family index page, the families listed by category."""
    num_archs = sum(len(d.archs) for d in families)
    num_weights = sum(len(d.weights) for d in families)
    out = [
        _GENERATED_NOTE,
        '',
        '# Model Families',
        '',
        f'`timm` has {num_archs} architectures in {len(families)} model families, with {num_weights} pretrained '
        'weights. Each family page lists the papers, architectures and pretrained weights of a model module, and '
        'which parts of the [Model API](model_api) its models support. See the [Quickstart](quickstart) for '
        'loading and using the models, the [models reference](reference/models) for `create_model` and the '
        'pretrained configs, and the [results](results) for the ImageNet validation results of all weights.',
        '',
    ]
    for category, category_title in CATEGORIES.items():
        members = sorted((d for d in families if d.spec['category'] == category), key=lambda d: d.spec['title'].lower())
        if not members:
            continue
        out += [f'## {category_title}', '']
        for d in members:
            counts = f'{_plural(len(d.archs), "architecture")}, {_plural(len(d.weights), "weight")}'
            out.append(f'* [{_md(d.spec["title"])}](models/{d.slug}) ({counts}): {d.spec["description"]}')
        out.append('')
    return '\n'.join(out)


def splice_matrix(page: Path, matrix: str) -> Optional[str]:
    """Return ``page`` with ``matrix`` between the generated support matrix markers, or None if not applicable."""
    if not page.exists():
        return None
    text = page.read_text()
    begin, end = text.find(_MATRIX_BEGIN), text.find(_MATRIX_END)
    if begin < 0 or end < begin:
        return None
    return text[:begin + len(_MATRIX_BEGIN)] + '\n' + matrix + text[end:]


# --------------------------------------------------------------------------------------------------------------------


def wrap_markdown(text: str, width: int = 120) -> str:
    """Wrap prose and list item lines of generated markdown to the docs line length.

    Tables, headings, code blocks and lines that are already short enough are left as is. Inline code and links are
    never split.

    Args:
        text: Markdown text.
        width: Maximum line length.

    Returns:
        The wrapped text.
    """
    out = []
    in_code = False
    for line in text.split('\n'):
        if line.lstrip().startswith('```'):
            in_code = not in_code
            out.append(line)
            continue
        if in_code or len(line) <= width or line.lstrip().startswith(('|', '#')):
            out.append(line)
            continue
        stripped = line.lstrip()
        indent = line[:len(line) - len(stripped)]
        bullet = re.match(r'([-*] |\d+\. )', stripped)
        subsequent = indent + ' ' * (len(bullet.group(1)) if bullet else 0)
        out.append(textwrap.fill(
            stripped,
            width=width,
            initial_indent=indent,
            subsequent_indent=subsequent,
            break_long_words=False,
            break_on_hyphens=False,
        ))
    return '\n'.join(out)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument(
        '--families', nargs='+', default=None, choices=sorted(FAMILIES), metavar='SLUG',
        help='families to generate, default all. The support matrix is only updated when all are generated')
    parser.add_argument('--output-dir', type=Path, default=_DOCS_SOURCE / 'models', help='family page directory')
    parser.add_argument('--results-dir', type=Path, default=_REPO_ROOT / 'results', help='results csv directory')
    parser.add_argument('--benchmark-csv', type=Path, default=None, help='benchmark csv for params / GMACs')
    parser.add_argument(
        '--matrix-file', type=Path, default=None,
        help='also write the support matrix to this file')
    parser.add_argument(
        '--index-page', type=Path, default=_DOCS_SOURCE / 'models.mdx',
        help='model family index page, written when all families are generated')
    parser.add_argument(
        '--model-api-page', type=Path, default=_DOCS_SOURCE / 'model_api.mdx',
        help='page to splice the support matrix into, if it has the generated support matrix markers')
    parser.add_argument('--no-probe', action='store_true', help='skip the model API probe (no support tables)')
    parser.add_argument(
        '--num-threads', type=int, default=1,
        help='torch CPU threads for the probe. The probed models are small, more threads mostly add overhead and are '
             'very slow on a busy machine')
    parser.add_argument('--check', action='store_true', help='do not write, exit 1 if any output is out of date')
    parser.add_argument('-v', '--verbose', action='store_true', help='print data issues')
    args = parser.parse_args(argv)

    if _REPO_ROOT not in Path(timm.__file__).resolve().parents:
        print(f'timm imported from {timm.__file__}, not this repository. Run with PYTHONPATH={_REPO_ROOT}.',
              file=sys.stderr)
        return 2
    logging.getLogger('timm').setLevel(logging.ERROR)
    warnings.filterwarnings('ignore')
    torch.set_grad_enabled(True)
    if args.num_threads > 0:
        torch.set_num_threads(args.num_threads)

    t0 = time.perf_counter()
    slugs = args.families or list(FAMILIES)
    covered = {m for slug, spec in FAMILIES.items() for m in spec.get('modules') or (slug.replace('-', '_'),)}
    missing = sorted(set(list_modules()) - covered)
    if missing:
        print(f'warning: model modules without a FAMILIES entry (no docs page): {", ".join(missing)}')
    results = load_results(args.results_dir / 'results-imagenet.csv')
    bench_path, benchmark = load_benchmark(args.results_dir, timm.list_models(), args.benchmark_csv)
    print(f'timm {timm.__version__} from {Path(timm.__file__).parent}, benchmark data {bench_path}')

    families = []
    outputs: Dict[Path, str] = {}
    for slug in slugs:
        print(f'{slug}:')
        data = collect_family(slug, FAMILIES[slug], results, benchmark, probe=not args.no_probe)
        families.append(data)
        outputs[args.output_dir / f'{slug}.mdx'] = render_family(data, results)
        print(f'  {len(data.archs)} architectures, {len(data.weights)} weights, {len(data.papers)} papers, '
              f'{len(data.issues)} data issues')
        if args.verbose:
            for issue in data.issues:
                print(f'    {issue}')

    if set(slugs) == set(FAMILIES):
        outputs[args.index_page] = render_index(families)
    else:
        print('index page not updated (needs all families)')
    if args.no_probe or set(slugs) != set(FAMILIES):
        # the matrix covers every family, a partial run would drop rows
        print('support matrix not updated (needs all families and the probe)')
    else:
        matrix = render_support_matrix(families)
        if args.matrix_file is not None:
            outputs[args.matrix_file] = matrix
        spliced = splice_matrix(args.model_api_page, matrix)
        if spliced is not None:
            outputs[args.model_api_page] = spliced

    stale = []
    for path, text in outputs.items():
        text = wrap_markdown(text)
        if path.exists() and path.read_text() == text:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    action = 'out of date' if args.check else 'written'
    for path in stale:
        print(f'{action}: {path}')
    print(f'done in {time.perf_counter() - t0:.1f}s')
    return 1 if args.check and stale else 0


if __name__ == '__main__':
    sys.exit(main())
