name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: pytorch-image-models
      package_name: timm
      path_to_docs: pytorch-image-models/hfdocs/source
      version_tag_suffix: ""
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
